### ISSUE TITLE
Spinning progress wheel not in one line

### ISSUE THREAD

**Issue by mingxiao** [vmware-tanzu/tanzu-framework#1016]
The progress wheel is outputting multiple lines
![Screen Shot 2021-10-29 at 10 31 31 AM](https://user-images.githubusercontent.com/1500022/139489588-5aa4766d-e9c2-4f53-a7bf-7992189f8de6.png)
**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security

- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
The progress wheel should be in one line

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)
```
version: v0.8.0
buildDate: 2021-10-22
sha: 6e2b6998
```

**Environment where the bug was observed (cloud, OS, etc)**
Desktop, using iterm2 `Build 3.4.12`
**Relevant Debug Output (Logs, manifests, etc)**

**Comment by danniel1205** [comment]
Hi @mingxiao , thanks for reporting this issue. Could you please share from which command you saw this ? I am guessing it is `tanzu package repository add` ?

**Comment by maralavi** [comment]
@mingxiao mentioned this is for adding repository and it his env is iterm 2 Build 3.4.12

**Comment by blc1996** [comment]
Fix merged
