### ISSUE TITLE
Make tanzu commands less verbose on CI systems

### ISSUE THREAD

**Issue by jvalkeal** [vmware-tanzu/tanzu-framework#1026]
**Describe the feature request**
When issuing commands like `tanzu package install <blaah>` or any other command which "waits" for reconciling to succeed or fail, output is different on a user shell vs. CI system. For example on Github Actions when running package install you get 1000+ lines printed:

![tanzu-package-install-ci-verbose](https://user-images.githubusercontent.com/50398/139535732-e0f2b4cf-e9cd-4298-b0b2-02175776f12e.png)

It'd be really nice if all `tanzu` commands would have a flag to squash/silence this running output or/and track common `CI` environment variable to do a same thing. This way CI system output would be much more easier to follow.
**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

Env from tce 0.9.1:
```
$ tanzu version
version: v0.2.1
buildDate: 2021-09-29
sha: ceaa474
```

**Comment by stmcginnis** [comment]
Related: https://github.com/vmware-tanzu/tanzu-framework/issues/43

**Comment by maralavi** [comment]
Relate #https://github.com/vmware-tanzu/tanzu-framework/issues/789

**Comment by danniel1205** [comment]
duplicate with #1016
