### ISSUE TITLE
A dangerous assumption is made when creating a new machine deployment that the first MD to be returned can be used as the base

### ISSUE THREAD

**Issue by nickperry** [vmware-tanzu/tanzu-framework#1067]
**Bug description**

https://github.com/vmware-tanzu/tanzu-framework/blob/fe23cf4d8a1d33251ebf2599b408419122a34808/pkg/v1/tkg/client/machine_deployment.go#L127

	workerMDs, err := clusterClient.GetMDObjectForCluster(options.ClusterName, options.Namespace)
	baseMD := workerMDs[0]

workerMDs[0] is not necessarily a good machine deployment to use as a template for a new machine deployment.

There used to be a similar assumption made in earlier versions of this code: https://github.com/vmware-tanzu/tanzu-framework/blob/v0.1.0/pkg/v1/tkg/client/machine_deployment.go#L82

This is causing a big problem for us as a TKGM 1.4 customer. If we try and create a new node pool, Tanzu picks up the wrong MD and we end up with a mess. For example, we have an existing dedicated node pool / md for Istio gateway nodes, which has specific labels and whose machines are in a dedicated DMZ network. In one of our environments, if I try to create a new node pool via the tanzu CLI, tanzu bases the new MD on the istio-gateway MD, and our new nodes end up with unwanted labels and are built in the wrong network. We cannot therefore use the node pool abstraction via the tanzu cli and instead have to work directly with machine deployment resources on the management cluster (which works fine).

It seems to me it would be a better idea to explicitly annotate an MD as being the one to use as a template, rather than just using workerMDs[0].

@tenczar 
**Affected product area (please put an X in all that apply)**

- [x] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
I should be able to create additional node pools based on a stable, explicitly defined base machine deployment.

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)
Seen on 1.4.0 and seems to be present on main.

**Environment where the bug was observed (cloud, OS, etc)**
Vsphere 7 TKGM 1.4

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by tenczar** [comment]
I agree whole heartedly that a more explicit means of selecting a base machine deployment is necessary. I will work on a quick fix that will allow a user to specify the desired machine deployment when creating a node pool to be added to 1.4.1. This will likely involve a new flag on the cli that accepts the name of a machine deployment and sets a warning in stderr if the flag is not provided. @timothysc Is a change like this to the cli UX acceptable? In the mean time a temporary workaround would be to rename your custom machine deployment to something alphanumerically lower than the tanzu defined machine deployments as the machine deployments are always listed in alphanumeric order.

**Comment by nickperry** [comment]
Thanks @tenczar .

I like your proposal of a new CLI flag to select the base. I also think it would be a good idea to annotate one MD as the default base to template from, for when new CLI flag is not used.
