### ISSUE TITLE
Add empty 04_user_customizations directory for end users

### ISSUE THREAD

**Issue by benjaminapetersen** [vmware-tanzu/tanzu-framework#1068]
**Bug description**

The /providers/ytt/ directory is copied to a users ~/.config/tanzu/tkg/providers/ytt. The [documentation encourages users to create an 04_user_customizations](https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.3/vmware-tanzu-kubernetes-grid-13/GUID-ytt.html?hWord=N4IghgNiBcIAwBYD6BXAzgUwE5IMboBcB7AWwEsAvMAsogOzRAF8g) within this directory for additional configuration that they may provide via templates. Users may miss this point in the docs and/or forget and then modify other files, such as those in /providers/ytt/03_customizations. Therefore, it seems better if we provide this directory by default. It may be self-documenting in several ways:

Encourage/remind users to put their customizations in the correct place
Encourage/remind users not to touch built-in configuration files

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [x] User Experience

**Comment by benjaminapetersen** [comment]
#457 opened to address the issue.

**Comment by saji-pivotal** [comment]
@benjaminapetersen Thanks for filing this issue and opening a PR. Assigning the issue to you as well.
