### ISSUE TITLE
Add ClusterResourceSet to install core-management-plugins package

### ISSUE THREAD

**Issue by anujc25** [vmware-tanzu/tanzu-framework#1110]
**Describe the feature request**
We need a way to install core-management-plugins management package in the management cluster, this can be done by creating a PackageInstall CR that refers core-management-plugins management package.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [x] Installation
- [x] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

**Comment by danniel1205** [comment]
@anujc25 , I am guessing this [PR](https://github.com/vmware-tanzu/tanzu-framework/pull/1046) fixed this issue, correct ?

**Comment by anujc25** [comment]
Yes. Closing this.
