### ISSUE TITLE
Kickstart UI: Confirmation settings heading typo

### ISSUE THREAD

**Issue by garrying** [vmware-tanzu/tanzu-framework#1183]
**Bug description**
- After stepping through the Wizard for `Docker` and clicking on `Review Configuration` the user is presented a series of tables to confirm the configuration
- The heading for cluster settings contains a doubled `settings` at the end of the string:
![Screen Shot 2021-11-16 at 3 47 50 PM](https://user-images.githubusercontent.com/227587/142063241-0d7ba50e-93b9-403a-be62-a90c44d844c2.png)
- Only checked with Docker; unsure if it's an issue with other providers
- Applicable for both standalone and management cluster configuration

**Affected product area (please put an X in all that apply)**

- [x] User Experience

**Expected behavior**
- `Management Cluster Settings settings` -> `Management Cluster settings`

**Steps to reproduce the bug**
- `tanzu management-cluster create --ui`
- `Navigate to http://127.0.0.1:8080/#/ui/docker/wizard`
- Step through wizard, click `Review Configuration`
- Note the heading of the second table

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by stmcginnis** [comment]
@miclettej should this be moved to `tanzu-framework`?

**Comment by miclettej** [comment]
Hi @stmcginnis you can close this issue. I noticed it while testing x509 bypass and fixed it in commit https://github.com/vmware-tanzu/tanzu-framework/commit/7b637c3dd4f8ac077b91a1ad5d1409f2296c554f

**Comment by stmcginnis** [comment]
Awesome, thanks @miclettej!
