### ISSUE TITLE
Use upstream antrea 

### ISSUE THREAD

**Issue by hangyan** [vmware-tanzu/tanzu-framework#1187]
(This is used to request new product features)

**Describe the feature request**
Since TCE is an open source project, it would be more reasonable to use upstream antrea's image ( and maybe other stuff too) as the default CNI solution.  If this is a fair request, there are other things worth considering:

* CI integration
* Kubernetes version matrix
* ...

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [x] Docs
- [ ] IAM
- [x] Installation
- [x] Plugin
- [ ] Security
- [x] Test and Release
- [x] User Experience

**Additional context**

**Comment by hangyan** [comment]
Links to : https://github.com/vmware-tanzu/community-edition/issues/2569

**Comment by knabben** [comment]
cc @edwardbadboy

**Comment by jayunit100** [comment]
i think we want this issue in the TCE repo, right?

**Comment by jayunit100** [comment]
@knabben

**Comment by jayunit100** [comment]
amim will respond on this one

**Comment by hangyan** [comment]
We can follow up on this one https://github.com/vmware-tanzu/community-edition/issues/2569

**Comment by blc1996** [comment]
Closing this one because it is being tracked in https://github.com/vmware-tanzu/community-edition/issues/2569
