### ISSUE TITLE
CODEOWNERS additions and cleanup

### ISSUE THREAD

**Issue by jayunit100** [vmware-tanzu/tanzu-framework#1195]
**Describe the feature request**

Add the @vmware-tanzu/tkg-infra-x  team to codeowners to create continuity and move away from single points of failure for reviews related to networking, windows, loadbalancing.

Along the way, also ensure there is a review team for docs, as well as clean up individual ids in the list when they are redundant.

**Describe alternatives you've considered**

Add individuals.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

**Comment by rajathagasthya** [comment]
@jayunit100 I'll assign this to you as you already have a PR to fix this.
