### ISSUE TITLE
`make init` fails on a pristine repository

### ISSUE THREAD

**Issue by mamachanko** [vmware-tanzu/tanzu-framework#1212]
**Bug description**

Calling `make init` on a pristine repository fails:

```shell
$ tanzu builder init my-plugin --repo-type github
$ cd my-plugin
$ make init
go mod download
go mod tidy
go mod download: github.com/vmware-tanzu/tanzu-framework@v1.4.0-pre-alpha-1.0.20210510133441-90ffe2e2a419: invalid version: unknown revision 90ffe2e2a419
gmake: *** [Makefile:20: go.mod] Error 1
```

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [x] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
I was hoping to be able to bootstrap a `tanzu` CLI plugin and learn more about how to write plugins. To that end I assumed that `make init` and then `make build` would get me there.

**Steps to reproduce the bug**
(see _Bug description_)

**Version** (include the SHA if the version is not obvious)
```
version: v0.11.0
buildDate: 2021-11-19
sha: 45c86526
```
**Environment where the bug was observed (cloud, OS, etc)**
```shell
$ uname -a
Darwin ***** 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64
```

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by mpanchajanya** [comment]
Not Reproducible. Its fixed
![Screen Shot 2022-08-26 at 14 34 04](https://user-images.githubusercontent.com/106101699/186979170-181912e3-e7da-417e-a357-61b48fc9d53f.png)
.
