### ISSUE TITLE
create namespace flag not working with package plugin

### ISSUE THREAD

**Issue by msrinivasssa** [vmware-tanzu/tanzu-framework#1258]
**Bug description**
create namespace flag is not working with package plugin. the namespace provided is not created. Repo is added to the global namespace and trying to install one of the package in a namespace which doesn't exist.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ x] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
Expected to create the namespace and install the package.
**Steps to reproduce the bug**

> ➜  beta-4 kubectl get ns
> NAME                        STATUS   AGE
> default                     Active   114m
> kapp-controller             Active   11m
> kube-node-lease             Active   114m
> kube-public                 Active   114m
> kube-system                 Active   114m
> secretgen-controller        Active   10m
> tanzu-package-repo-global   Active   11m
> tanzu-prereqs               Active   11m
> ➜  beta-4
> ➜  beta-4
> ➜  beta-4 tanzu package install tap-pkg -p tap.tanzu.vmware.com -v 0.4.0-build.8 -f tap-pkg-values.yaml -n tap-install --create-namespace
> \ Installing package 'tap.tanzu.vmware.com'
> - Getting package metadata for 'tap.tanzu.vmware.com'
> 
> Error: failed to find a package with name 'tap.tanzu.vmware.com' in namespace 'tap-install': internalpackagemetadatas.internal.packaging.carvel.dev "tap.tanzu.vmware.com" not found
> Error: exit status 1
> 
> ✖  exit status 1

> ➜  beta-4 kubectl get ns
> NAME                        STATUS   AGE
> default                     Active   124m
> kapp-controller             Active   21m
> kube-node-lease             Active   124m
> kube-public                 Active   124m
> kube-system                 Active   124m
> secretgen-controller        Active   20m
> tanzu-package-repo-global   Active   21m
> tanzu-prereqs               Active   22m

**Version** (include the SHA if the version is not obvious)

> ➜  beta-4 tanzu version
> version: v0.10.0
> buildDate: 2021-11-03
> sha: fd96bebe

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by maralavi** [comment]
@msrinivasssa Sees like you have not added the package repository to the "tap-install" namespace? Could you please share the command you used for adding the package repository and which namespace you have added the tap package repository to?
```
tanzu package repository list -A
```

**Comment by msrinivasssa** [comment]
@maralavi - you are right. the repo is added to the global namespace.

> ➜  beta-4 tanzu package repository list -A
> - Retrieving repositories...
>   NAME            REPOSITORY                                                             TAG                                                                      STATUS               DETAILS  NAMESPACE
>   tanzu-tap-repo  dev.registry.tanzu.vmware.com/tanzu-application-platform/tap-packages  sha256:679ae86d7ec10a6b8b07a393df5099f4ab244c3e344d39d8aff3dc74d3692c84  Reconcile succeeded           tanzu-package-repo-global

tap-install namespace is not created yet and i was expecting the namespace to be created with `--create-namespace` flag

Though i installed kapp-controller manually, it is same package that TKG uses and the global namespace is same.

> ➜  beta-4 kubectl get deployments -A | grep "kapp-controller"
> kapp-controller          kapp-controller                       1/1     1            1           21h
> ➜  beta-4 kubectl get deployments kapp-controller -n kapp-controller -o yaml | grep "global"
> 
>       registry.tanzu.vmware.com/tanzu-prerequisites/prereqs-bundle@sha256:083f0f526c4f9b5cb6e6506ad0a9c54a9b73209ab06906a6b6ae5872351048a0\n"},"labels":{"kapp.k14s.io/app":"1638253646700986000","kapp.k14s.io/association":"v1.fe52da16e0a51b0fd5db09d5419fc314"},"name":"kapp-controller","namespace":"kapp-controller"},"spec":{"replicas":1,"revisionHistoryLimit":0,"selector":{"matchLabels":{"app":"kapp-controller","kapp.k14s.io/app":"1638253646700986000"}},"template":{"metadata":{"labels":{"app":"kapp-controller","kapp.k14s.io/app":"1638253646700986000","kapp.k14s.io/association":"v1.fe52da16e0a51b0fd5db09d5419fc314"}},"spec":{"containers":[{"args":["-packaging-global-namespace=tanzu-package-repo-global","-concurrency=10","-metrics-bind-address=:8080"],"env":[{"name":"KAPPCTRL_MEM_TMP_DIR","value":"/etc/kappctrl-mem-tmp"},{"name":"KAPPCTRL_SYSTEM_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"KAPPCTRL_API_PORT","value":"10350"}],"image":"registry.tanzu.vmware.com/tanzu-prerequisites/prereqs-bundle@sha256:083f0f526c4f9b5cb6e6506ad0a9c54a9b73209ab06906a6b6ae5872351048a0","name":"kapp-controller","ports":[{"containerPort":10350,"name":"api","protocol":"TCP"}],"resources":{"requests":{"cpu":"120m","memory":"100Mi"}},"securityContext":{"runAsGroup":2000,"runAsUser":1000},"volumeMounts":[{"mountPath":"/etc/kappctrl-mem-tmp","name":"template-fs"}]}],"imagePullSecrets":[{"name":"kapp-controller-registry-creds"}],"securityContext":{"fsGroup":3000},"serviceAccount":"kapp-controller-sa","volumes":[{"emptyDir":{"medium":"Memory"},"name":"template-fs"}]}}}}'
>         - -packaging-global-namespace=tanzu-package-repo-global

my issue is case-2.

**Comment by maralavi** [comment]
@msrinivasssa Thanks for verifying. The PR for that is under review and it should be merged into tanzu-framework soon.

**Comment by shyaamsn** [comment]
Fixed by https://github.com/vmware-tanzu/tanzu-framework/pull/1263
