### ISSUE TITLE
Support installing plugins with local filesystem when `context-aware-cli-for-plugins` feature is enabled

### ISSUE THREAD

**Issue by anujc25** [vmware-tanzu/tanzu-framework#1264]
**Describe the feature request**

With the implementation of #1150, we have enabled the feature flag for context-aware-cli plugins discovery by default. With this, the tanzu CLI can discover and install plugins from OCI based image registry for official builds and from the local filesystem only during development.

As we currently only support local discovery and distribution for the development purpose because the local plugin discovery and distribution currently rely on absolute filesystem paths to be defined as part of CLIPlugin resources making it not usable for distribution and sharing among the different users.

The request is to propose a way to allow users to install standalone plugins from the local file system that can be distributed and downloaded as a tarball from a verified source and make them available to the tanzu cli when `context-aware-cli-for-plugins` feature is enabled.

**Describe alternatives you've considered**

Users can disable `context-aware-cli-for-plugins` the feature entirely and install the plugins from the local source however, as we made the feature enabled by default this doesn't seem like the right thing to do long term.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [x] Plugin
- [ ] Security
- [ ] Test and Release
- [x] User Experience

**Additional context**

**Comment by vuil** [comment]
Somewhat orthogonal, but this reminded me that the tarballs in the our release still contains the full set of plugins. What should the contents of the tars contain? What should they contain when this issue is addressed? cc @navidshaikh

**Comment by navidshaikh** [comment]
> What should they contain when this issue is addressed?

I don't think we'd need to change the contents of the tarball upon resolution of the issue. 

@anujc25 : Are we looking at a flag to switch the source of plugin installation? 
I think it'd be helpful to add some command line examples and table the precedence, something like
- command line flag takes precedence over global config / defaults

and actual UX of the flag
- bool flag (`--local-plugins`, `--gcs-plugins`) OR
- flag (`--source`) with a default value (`auto`) and allowed values: `local`, `gcs`

**Comment by anujc25** [comment]
Does it make sense to split the release artifacts into multiple tarballs/binary? cc @vuil @navidshaikh @rajaskakodkar 

Here is the proposed release artifacts and the UX for the user:

**Release Artifacts:**

**Darwin-amd64 bundle:**

1. tanzu-cli-darwin-amd64 (only the tanzu cli binary)
1. tanzu-cli-default-standalone-plugins-darwin-amd64.tar.gz (Check below for the sample content of the tarball)
1. tanzu-cli-admin-plugins-darwin-amd64.tar.gz (Optional)

**Linux-amd64 bundle:**

1. tanzu-cli-linux-amd64 (only the tanzu cli binary)
1. tanzu-cli-default-standalone-plugins-linux-amd64.tar.gz
1. tanzu-cli-admin-plugins-linux-amd64.tar.gz (Optional)

**Windows-amd64 bundle:**
1. tanzu-cli-windows-amd64.exe (only the tanzu cli binary)
1. tanzu-cli-default-standalone-plugins-linux-amd64.tar.gz
1. tanzu-cli-admin-plugins-linux-amd64.tar.gz (Optional)

**Tarball structure and content for darwin-amd64:**

```
$ tree /tmp/tanzu-plugins/
/tmp/tanzu-plugins/
├── discovery
│   └── standalone
│       ├── cluster.yaml
│       ├── kubernetes-release.yaml
│       ├── login.yaml
│       ├── management-cluster.yaml
│       ├── package.yaml
│       ├── pinniped-auth.yaml
│       └── secret.yaml
└── distribution
    └── darwin
        └── amd64
            └── cli
                ├── cluster
                │   └── v0.13.0-dev
                │       └── tanzu-cluster-darwin_amd64
                ├── kubernetes-release
                │   └── v0.13.0-dev
                │       └── tanzu-kubernetes-release-darwin_amd64
                ├── login
                │   └── v0.13.0-dev
                │       └── tanzu-login-darwin_amd64
                ├── management-cluster
                │   └── v0.13.0-dev
                │       └── tanzu-management-cluster-darwin_amd64
                ├── package
                │   └── v0.13.0-dev
                │       └── tanzu-package-darwin_amd64
                ├── pinniped-auth
                │   └── v0.13.0-dev
                │       └── tanzu-pinniped-auth-darwin_amd64
                └── secret
                    └── v0.13.0-dev
                        └── tanzu-secret-darwin_amd64
```

```
$ tree /tmp/tanzu-admin-plugins/
/tmp/tanzu-admin-plugins/
├── discovery
│   └── admin
│       ├── builder.yaml
│       ├── codegen.yaml
│       └── test.yaml
└── distribution
    └── darwin
        └── amd64
            └── cli
                ├── builder
                │   └── v0.13.0-dev
                │       └── tanzu-builder-darwin_amd64
                ├── codegen
                │   └── v0.13.0-dev
                │       └── tanzu-codegen-darwin_amd64
                └── test
                    └── v0.13.0-dev
                        └── tanzu-test-darwin_amd64
```

**Installation UX:**

As a tanzu cli user using MacOS, I can do the below steps to install cli and plugins:

1. Download and install the `tanzu-cli-darwin-amd64` binary
1. Install Plugins
    * **[Option-1] Install from OCI repository (Recommended)**
        1. Run `tanzu plugin sync` command which installs default-standalone-plugins from the OCI bucket
        1. Run `tanzu plugin list` to verify installed plugins
    * **[Option-2] To install the plugin from the local filesystem by downloading the tarball**
        1. Download `tanzu-cli-default-standalone-plugins-darwin-amd64.tar.gz` bundle and extract it to the mentioned location
        1. Run `tar -xvf tanzu-cli-default-standalone-plugins-darwin-amd64.tar.gz  -C $HOME/.config/tanzu-plugins` to extract the plugins to appropriate local plugin discovery location
        1. Run `tanzu plugin source add --type local --name standalone-default -source --uri standalone` to add local discovery source to tanzu config file
        1. Run `tanzu plugin sync` to install all available plugins from the local discovery source added in the previous step
        1. Run `tanzu plugin list` to verify installed plugins
        * NOTE: Installing plugin this way will make all plugins standalone plugins including `cluster` and `secret`. So, it is recommended that we use this method mainly for standalone plugins like admin-plugins

**Comment by vuil** [comment]
lgtm in general. I like that the install mechanism for local-based standalones are the same as admin.
The remaining question is what to do with cluster/kubernetes-release. Do we leave them out before they are of the context-aware category? Or do include them in a tarball for completeness, and if so, in what form? I need to chew on it a bit more.

**Comment by navidshaikh** [comment]
During a sync on this topic we also discussed about having `tanzu plugin sync --local` to install the plugins from filesystem. This could a convenient for users planning to always install/upgrade plugins from filesystem.

**Comment by sriramandev** [comment]
Based on the sync over the topic, another point to be noted. With the change in the structure of the binaries(artifacts), the upload to GCS bucket for the older way of plugin install to work cannot happen. So, either we also provide artifact the same way as previously(to allow push to GCS and that would mean four artifacts instead of three for each OS arch combination) or we no longer support the older approach going forward.

**Comment by anujc25** [comment]
>During a sync on this topic we also discussed about having tanzu plugin sync --local to install the plugins from filesystem. This could be convenient for users planning to always install/upgrade plugins from filesystem. 

I had an offline discussion with @vuil and here is the conclusion:

Even though the **[Option-2] To install the plugin from the local filesystem by downloading the tarball** mentioned above is one of the supported ways to install the plugins, our preference is to implement `tanzu plugin sync --local <path-to-local-dir>` as mentioned by @navidshaikh for easy one-time install of the plugins.

Installing plugins this way with the `--local` flag means, the installed plugins are not associated with any discovery mechanism. So, if the user deletes the installed plugin to reinstall these plugins user needs to use the same `tanzu plugin sync --local <path-to-local-dir>` command again. (This is expected but wanted to state this assumption clearly)

**Comment by danfein** [comment]
Chatted offline with @heyjcollins and @anujc25:

Recommended `tanzu plugin install all --local` over `tanzu plugin sync` when manually installing plugins.
Reasoning: 
  It keeps the install-one and install-many actions together (instead of using install for one, and sync for many)
  Sync felt like the wrong verb for a one-off install action, there is no post-install sync possible for manually installed plugins
  It keeps the two install paths clearly separated, the discover/sync actions for context-aware enabled plugins, and the install action for manually installed plugins. 
  
Notes:
  Given the proximity to GA, the apps plugin may or may not be able to make the changes to work with context-aware, so having a manual path is helpful, and it would let context-aware and manual plugins co-exist.

**Comment by anujc25** [comment]
Thanks, @danfein for the summary. I am adding the proposed UX here.

1. List the plugins without `--local`: Lists all available default plugins from OCI registry
```
$ tanzu plugin list
  NAME                DESCRIPTION                                                        SCOPE       DISCOVERY  VERSION      STATUS         
  login               Login to the platform                                              Standalone  default    v0.13.0-dev  not installed  
  management-cluster  Kubernetes management-cluster operations                           Standalone  default    v0.13.0-dev  not installed  
  package             Tanzu package management                                           Standalone  default    v0.13.0-dev  not installed  
  pinniped-auth       Pinniped authentication operations (usually not directly invoked)  Standalone  default    v0.13.0-dev  not installed  
  secret              Tanzu secret management                                            Standalone  default    v0.13.0-dev  not installed 
```

2. List the plugins with `--local` pointing to admin plugin: Lists only available admin-plugins from local file-system
```
$ tanzu plugin list --local /tmp/admin/tanzu-plugins/
  NAME     DESCRIPTION                 SCOPE       DISCOVERY  VERSION      STATUS         
  builder  Build Tanzu components      Standalone             v0.13.0-dev  not installed  
  codegen  Tanzu code generation tool  Standalone             v0.13.0-dev  not installed  
  test     Test the CLI                Standalone             v0.13.0-dev  not installed 
```

3. Install plugins with `all` and `--local`: Only installs admin-plugin from given local file-system and doesn't install default plugins from OCI registry
```
$ tanzu plugin install all --local /tmp/admin/tanzu-plugins/
Installing plugin 'builder:v0.13.0-dev'
Installing plugin 'codegen:v0.13.0-dev'
Installing plugin 'test:v0.13.0-dev'
Successfully installed all plugins
✔  successfully installed 'all' plugin
```

4. Lists all installed plugins. Plugins installed with `tanzu plugin install all --local /tmp/admin/tanzu-plugins/` will not display `DISCOVERY` information, but will be listed as part of `list` command output
```
$ tanzu plugin list
  NAME                DESCRIPTION                                                        SCOPE       DISCOVERY  VERSION      STATUS         
  login               Login to the platform                                              Standalone  default    v0.13.0-dev  not installed  
  management-cluster  Kubernetes management-cluster operations                           Standalone  default    v0.13.0-dev  not installed  
  package             Tanzu package management                                           Standalone  default    v0.13.0-dev  not installed  
  pinniped-auth       Pinniped authentication operations (usually not directly invoked)  Standalone  default    v0.13.0-dev  not installed  
  secret              Tanzu secret management                                            Standalone  default    v0.13.0-dev  not installed  
  builder             Build Tanzu components                                             Standalone             v0.13.0-dev  installed      
  codegen             Tanzu code generation tool                                         Standalone             v0.13.0-dev  installed      
  test                Test the CLI                                                       Standalone             v0.13.0-dev  installed    
```

5. Clean all installed plugins with `tanzu plugin clean` will delete all installed plugins
6. Listing plugin after deleting all plugin will not show locally installed plugins
```
$ tanzu plugin list
  NAME                DESCRIPTION                                                        SCOPE       DISCOVERY  VERSION      STATUS         
  login               Login to the platform                                              Standalone  default    v0.13.0-dev  not installed  
  management-cluster  Kubernetes management-cluster operations                           Standalone  default    v0.13.0-dev  not installed  
  package             Tanzu package management                                           Standalone  default    v0.13.0-dev  not installed  
  pinniped-auth       Pinniped authentication operations (usually not directly invoked)  Standalone  default    v0.13.0-dev  not installed  
  secret              Tanzu secret management                                            Standalone  default    v0.13.0-dev  not installed
```

cc @vuil @navidshaikh @danfein @heyjcollins

**Comment by vuil** [comment]
LGTM. 

Please clarify the behavior when the plugins installed --local-ly are also part of some discovery source, such as:

- what will ```tanzu plugin list``` display
- what happens after  ```tanzu plugin sync``` in that case

Also, please document the behavior of ```tanzu plugin sync``` when those plugins are _not_ part of any discovery source.
(IIUC, sync will have no effect on those plugins)

**Comment by anujc25** [comment]
Documented this behavior as part of the PR https://github.com/vmware-tanzu/tanzu-framework/pull/1278/files. cc @vuil
