### ISSUE TITLE
Integrate CodeQL analysis

### ISSUE THREAD

**Issue by navidshaikh** [vmware-tanzu/tanzu-framework#1287]
**Describe the feature request**
Integrate CodeQL scan via a github action to run at a regular interval.
From https://codeql.github.com/
```
Discover vulnerabilities across a codebase with CodeQL,
our industry-leading semantic code analysis engine.
CodeQL lets you query code as though it were data.
Write a query to find all variants of a vulnerability, eradicating it forever.
Then share your query to help others do the same.

CodeQL is free for research and open source.
```
also available as github action: https://github.com/github/codeql-action

**Describe alternatives you've considered**
Dependabot, which is already integrated with the repo. CodeQL provides additional analysis and surfaces any probable improvements we can make in the code.
 
**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [x] Security
- [x] Test and Release
- [ ] User Experience

**Additional context**

**Comment by navidshaikh** [comment]
A sample run of CodeQL and results integration on github: 
github action run: https://github.com/navidshaikh/tanzu-framework/actions/workflows/security.yaml
results: https://github.com/navidshaikh/tanzu-framework/security/code-scanning

**Comment by navidshaikh** [comment]
cc: @dims

**Comment by dims** [comment]
Nice @navidshaikh !

**Comment by rajathagasthya** [comment]
Curious: does this provide more robust scanning compared to `gosec` linter we already run?

**Comment by navidshaikh** [comment]
yes @rajathagasthya, PTAL at the recent run of the scan https://github.com/vmware-tanzu/tanzu-framework/pull/1295/checks?check_run_id=4420959162 it could find a couple of issues with go code and a bunch of other for javascript (cc: @miclettej )
