### ISSUE TITLE
Review vendirsync from Antrea TCE commit

### ISSUE THREAD

**Issue by knabben** [vmware-tanzu/tanzu-framework#1315]
**Bug description**

There's a discrepancy between the Antrea the TCE commit hash and this repository artifacts, a `vendir sync` must be made and the proper layer added for configuration override.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [x] Installation
- [x] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
A correct configuration overlay be added on top of vendir synced directory

**Steps to reproduce the bug**
Check the configuration is not overlayed

**Version** (include the SHA if the version is not obvious)
0.11.0 - 0.12.0

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by swalner-vmware** [comment]
At this time, we do not have an `area/installation` label, so I have labeled this `area/addons` and `area/release`, although the latter may be inaccurate.
