### ISSUE TITLE
Check: Integrate yaml linter

### ISSUE THREAD

**Issue by navidshaikh** [vmware-tanzu/tanzu-framework#1322]
**Describe the feature request**
Integrate yaml linter github action to report any yaml lint issues. Have a configuration file to control what can be reported.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [x] Test and Release
- [ ] User Experience

**Additional context**
Port yamllinter from TCE https://github.com/vmware-tanzu/community-edition/actions/workflows/check-yaml.yaml

**Comment by aman556** [comment]
I am interested in this issue as i had done the same thing earlier.

**Comment by Akasurde** [comment]
@navidshaikh Do you think we can close this issue as PR #1410 is merged?

**Comment by navidshaikh** [comment]
Fixed by #1410

**Comment by Akasurde** [comment]
@aman556 Thanks for the contribution.
