### ISSUE TITLE
Kickstart UI: Import TCE .md docs into contextual help topics 

### ISSUE THREAD

**Issue by miclettej** [vmware-tanzu/tanzu-framework#1361]
TCE would like to populate in-app contextual help topics using existing official docs content. This issue is created to track the effort for determining a method to partially automate conversion of selected .md docs files into contextual help content.

The idea is to use a 3rd party library or write a custom script to extract identified .md files in the TCE repo docs into HTML content within the kickstart UI. Some investigation will have to be done to determine options for automating this process.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [ ] CLI
- [x] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [x] User Experience

**Additional context**

**Comment by kcoriordan** [comment]
I added sample files to experiment with here:

`pre-reqs.md `and `step-1.md` should map to first panel
`step-2.md, step-3.md, step-4.md, step-5.md, step-6.md, step-7.md` should map to corresponding panels
`final-step.md` should map to the REVIEW CONFIGURATION button
