### ISSUE TITLE
Improve proportion of valid generated testcases for clustergen

### ISSUE THREAD

**Issue by vuil** [vmware-tanzu/tanzu-framework#1377]
**Bug description**

clustergen diffs are most effective when where is a good mix of valid and invalid testcases.
some recent changes in overlays or validation logic have rendered more configurations to be invalid.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [x] Test and Release
- [ ] User Experience

**Expected behavior**

restore to close to 50/50 mix of valid and invalid test cases.

**Steps to reproduce the bug**
```
make clustergen
cat new/failed.txt | cut -d: -f2 | sort | grep -v failed | uniq -c
```

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by mcwumbly** [comment]
@vuil I just had a thought: I wonder if we could maintain separate files to generate valid configs vs. invalid configs? and separately report the results? do you think that'd be feasible and/or valuable?
