### ISSUE TITLE
`tanzu init` and `tanzu update` command doesn't respect `context-aware-cli-for-plugins` feature flag

### ISSUE THREAD

**Issue by anujc25** [vmware-tanzu/tanzu-framework#1411]
**Bug description**

`tanzu init` and `tanzu update` command doesn't respect `context-aware-cli-for-plugins` feature flag. 

This allows unpredictable behavior of tanzu cli because running this command tries to install old plugins sometimes with `tanzu init` from GCP bucket depending on the `repositories` configuration under config file.

Running `tanzu update` tries to download tanzu-cli from the GCP bucket.

As when `context-aware-cli-for-plugins` feature flag is enabled, tanzu cli doesn't rely on GCP bucket or the `repositories` configuration under config.yaml file, it should not download and install plugins from GCP bucket. 

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

- `tanzu init` will sync/update all available plugins for the user based on `context-aware-cli-for-plugin` feature
- `tanzu update` should not rely on the GCP bucket when `context-aware-cli-for-plugin` feature flag is enabled

**Steps to reproduce the bug**

- Run below commands:
- `tanzu init`
- `tanzu update`

**Version** (include the SHA if the version is not obvious)
v0.14.0

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by vuil** [comment]
Given the context-aware-cli-for-plugin, converting init to sync feels reasonable.
We probably need to rethink how self-update with ```tanzu update``` should behave. The current behavior of updating the core binary via the GCP bucket does conflict with the discovery source model, and should not be continued. Until we have a better solution, it is probably a good idea to log that this functionality is not supported.
