### ISSUE TITLE
Kickstart UI: refactor TkgEvent and TkgEventType to remove "Tkg"

### ISSUE THREAD

**Issue by swalner-vmware** [vmware-tanzu/tanzu-framework#1437]
**Bug description**
To help remove TKG references in the open source repo, rename TkgEvent and TkgEventType (and any other TKG-named classes)

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [X] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by miclettej** [comment]
Hi @2022amanda please locate and rename the TkgEvent and TkgEventType to TanzuEvent and TanzuEventType
