### ISSUE TITLE
Generated files cause dirty file verification failure due to new year

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/tanzu-framework#1442]
**Bug description**

When we generate files using `make generate` that creates the file with our copyright header. The header includes the current year as part of that statement, so with the new year it causes those files to be flagged as dirty and causes verification to fail.

We should consider if this is the behavior we want, but in the meantime we just need to update the files to be good for another year.

**Steps to reproduce the bug**

Run `make generate`, observe the file differences with `git diff`.

**Comment by vuil** [comment]
Thanks for filing the issue and the fix. Ok to close or are we exploring alternatives?

**Comment by stmcginnis** [comment]
Yeah, I guess so. I wanted to spend a little time thinking of a more elegant solution to this, but it looks like we may be stuck just needing to remember to do this at the start of each year.

The `make generate` target uses controller-gen to generate a few source files, using `hack/boilerplate.go.txt` as a template. The make target looks up the current year and passes that in to controller-gen where it updates the source file header with the current copyright.

We _could_ hard code a YEAR in there, but that doesn't seem right that it would potentially be pulling in newer code but putting an older copyright on it.

Since this is generated code, we could exclude the copyright header. But that doesn't seem quite right either, and we would need to update policies and our header linting check to exclude these files.

So the path of least resistance is probably to just make this update at the start of each year. Maybe in 2023 we will have new ideas or a fresh perspective, but I think we can close this for now.
