### ISSUE TITLE
Consider using /api to test if the CLIPlugin CRD exists

### ISSUE THREAD

**Issue by mayankbh** [vmware-tanzu/tanzu-framework#1448]
**Describe the feature request**

The [current](https://github.com/vmware-tanzu/tanzu-framework/blob/e91b85fdc9c7ae4a67ac47dcdb20d92de7c70186/pkg/v1/tkg/clusterclient/clusterclient.go#L2309-L2313) CLIPlugin discovery logic appears to rely on a GET request for a CustomResourceDefinition to determine if the target cluster supports CLIPlugins. 

This results in the assumption that the user performing login has permissions to get CRD objects. In an environment where, say, a user only has permissions on a single namespace in the target cluster, such users may not have the appropriate privileges to GET CRDs (cluster scoped), and plugin discovery fails.

Since it's possible as an authenticated user to access the /apis endpoint, would it make sense to use that approach for testing if CLI plugins exist? I haven't thought too hard about whether that's a more brittle contract, admittedly.

**Describe alternatives you've considered**

Granting permissions to GET CRDs (or only GET the CLIPlugin CRD via the resourceNames capability) is an option but requires granting additional privileges, or creating a new clusterrole/clusterrolebinding at the very least.

I concede that the ability for users to GET CLIPlugins is required regardless, but that's separate from the ability to get CRDs, I think.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [X] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [X] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

**Comment by rajathagasthya** [comment]
This seems reasonable. @anujc25 I think you can substitute `Object` query with a [GVR](https://github.com/vmware-tanzu/tanzu-framework/blob/151cf2e34b74cc839735cc316f2495e9702d3c3c/pkg/v1/sdk/capabilities/discovery/cluster_gvr.go#L16-L21) query for this.
