### ISSUE TITLE
`go get github.com/vmware-tanzu/tanzu-framework@<SHA>` gets a version that is based off `v1.4.0-pre-alpha-2`

### ISSUE THREAD

**Issue by rajathagasthya** [vmware-tanzu/tanzu-framework#1556]
**Bug description**

When Go modules that add tanzu-framework try to get a specific commit that's not tagged, it results in a version which looks like `v1.4.0-pre-alpha-2.0.<datetime>.<sha>`. This version is confusing and indicates to consumers that it's the most recent version of the repo (which is not true). Example: any plugin created using `tanzu builder`.

This happens because of the `v1.4.0-pre-alpha-*` legacy tags in this repo, which were created before `v0.1.0`. This can be fixed by `retract` directive of go modules.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [x] Test and Release
- [ ] User Experience

**Expected behavior**

`go get github.com/vmware-tanzu/tanzu-framework@<SHA>` should result in a version based off the latest tag (`v0.X.Y`) instead of a legacy tag.

**Steps to reproduce the bug**

Create a plugin using `tanzu builder init` and do `go mod tidy` to see tanzu-framework dependency listed as the version described above. 

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by navidshaikh** [comment]
Thanks! This takes care of retracting these tags while working go modules, logged https://github.com/vmware-tanzu/tanzu-framework/issues/1564 to track removing the git tags as well.
