### ISSUE TITLE
Clusterbootstrap controller might want to specify more fields on PackageInstall CR creation

### ISSUE THREAD

**Issue by danniel1205** [vmware-tanzu/tanzu-framework#1677]
(This is used to request new product features)

**Describe the feature request**

`clusterbootstrap_controller` creates or patches PackageInstall CR for kapp-controller on the mgmt cluster and for other bootstrap packages on the workload cluster. As MVP, we only fill the minimum required fields. It is a good idea to do some research and see if any other fields need to be specified, i.e., `ext.packaging.carvel.dev/ytt-data-values-overlays` annotations, `pkgi.Spec.SyncPeriod`, etc.

**Describe alternatives you've considered**

NA

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

**Comment by danniel1205** [comment]
Related issue: https://github.com/vmware-tanzu/tanzu-framework/issues/1738

**Comment by shivaani0505** [comment]
Change sync_period to 5 min
