### ISSUE TITLE
Clusterbootstrap controller might want to preserve other fields of Package CR when copying it to workload cluster

### ISSUE THREAD

**Issue by danniel1205** [vmware-tanzu/tanzu-framework#1678]
(This is used to request new product features)

**Describe the feature request**

`clusterbootstrap_controller` copies Package CR from mgmt cluster to workload clusters. As MVP, we only preserve minimum fields. We need to check if other fields need to be preserved as well.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

**Comment by shivaani0505** [comment]
Tracked using https://github.com/vmware-tanzu/tanzu-framework/issues/1677, so closing this one
