### ISSUE TITLE
Clusterbootstrap controller needs to handle inline data value from ClusterBootstrapPackage

### ISSUE THREAD

**Issue by danniel1205** [vmware-tanzu/tanzu-framework#1694]
(This is used to request new product features)

**Describe the feature request**

There are three types of data value could be provided in ClusterBootstrapPackage: SecretRef, ProviderRef, Inline. Current implementation covers only SecretRef and ProviderRef. We also need to handle the inline case.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

**Comment by vijaykatam** [comment]
Copying from 


1. Change https://github.com/vmware-tanzu/tanzu-framework/blob/main/apis/run/v1alpha3/clusterbootstraptemplate_types.go#L50 to map[string]interface{}

2. OSImage type https://github.com/vmware-tanzu/tanzu-framework/blob/main/apis/run/v1alpha3/osimage_types.go#L41 handles with a custom DeepCopy https://github.com/vmware-tanzu/tanzu-framework/blob/main/apis/run/v1alpha3/osimage_types.go#L45

The config should be cloned into ClusterBootstrap and copied over as a secret to workload cluster
