### ISSUE TITLE
vSphere Template Resolver: cluster webhook to resolve the ova version to existing template in vSphere

### ISSUE THREAD

**Issue by prkalle** [vmware-tanzu/tanzu-framework#1716]
Code to implement vSphere template resolver webhook AND package manifests to produce Carvel packages. This webhook should be packaged into `tkr-vsphere-cluster-webhook` package.

## Details
Currently the logic of resolving the vSphere template using the ova version is in CLI client code. This should be moved to server side. So the vSphere template resolver webhook should resolve the vSphere template name existing on vSphere using the `ova version` and the `osinfo` 

This component is a mutating webhook on Cluster resources:

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
```

If the `TKR_DATA` variable is present in the cluster topology, the webhook should do the following to the `TKR_DATA` value (see [tkrdata.go](https://github.com/vmware-tanzu/tanzu-framework/blob/main/pkg/v2/tkr/webhook/cluster/tkr-resolver/cluster/tkrdata.go)) in `.spec.topology.variables` and all of its overrides in `.spec.topology.workers.machineDeployments[*].variables.overrides`:

- For each mapping in the form of `kubernetesVersion: tkrDataValue`:
  - Read the `osImageRef.version` and also read the `datacenter`, `server` from cluster variables and get the vSphere credentials from `identityRef` secret. It should also use the following labels from the same tkrDataValue:
    - `os-type`
    - `os-name`
    - `os-version`
    - `os-arch`
  - After acquiring all the data it should connect to the target vSphere and resolve the templates available on the target cluster. 
The resolved template path and moID should be added to the `osImageRef` map (alongside `version`):
    - `template`
    - `moId`

The webhook should be installable as a Carvel package named `tkr-vsphere-cluster-webhook`.

**Comment by imikushin** [comment]
Note: the OSInfo labels (`os-type`, `os-name`, `os-version`, `os-arch`) will be set by the TKR Resolver webhook in controlPlane and machineDeployment metadata in the Cluster topology.
