### ISSUE TITLE
TKG client library makes assumption about standard-package-repo existence when doing upgrades, breaking TCE cluster upgrades

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/tanzu-framework#1749]
**Bug description**

When users in TCE attempt to upgrade their clusters, they will see:

```
Error: unable to upgrade management cluster: failed to update metadata configmaps after kubernetes upgrade: error while upgrading additional component 'addons-management/standard-package-repo': kubectl apply failed, output: error: no objects passed to apply : exit status 1
```

The standard-package-repo does **not** exist for TCE clusters.

Talking to @shivaani0505, they said:

> Issue is at the following line: https://github.com/vmware-tanzu/tanzu-framework/blob/main/pkg/v1/tkg/client/upgrade_addon.go#L252 when handling upgrade.
> So the manifest file is empty when BUILD is TCE. Applying empty file results in that error.
> I verified it by also running the below command on cluster and it returns the same error as you are getting:
>
> echo "" | kubectl apply -f -
> error: no objects passed to apply

For TCE, we need this fix backported into a new patch release, `v0.11.2` in order to support https://github.com/vmware-tanzu/community-edition/issues/3285.

**Comment by tenczar** [comment]
In this list, what are the addons that do not apply to TCE https://github.com/vmware-tanzu/tanzu-framework/blob/20e50da2c8594b67df64029d974c75d0243715b3/pkg/v1/tkg/client/upgrade_cluster.go#L349 ?
