### ISSUE TITLE
Fix gocyclo issue from clusterbootstrap controller

### ISSUE THREAD

**Issue by danniel1205** [vmware-tanzu/tanzu-framework#1761]
**Bug description**

There are linter issue from CI pipeline that we have to fix it as a followup.
```
Error: controllers/clusterbootstrap_controller.go:178:1: cyclomatic complexity 18 of func `(*ClusterBootstrapReconciler).reconcileNormal` is high (> 15) (gocyclo)
func (r *ClusterBootstrapReconciler) reconcileNormal(cluster *clusterapiv1beta1.Cluster, log logr.Logger) (ctrl.Result, error) {
^
make: *** [Makefile:521: go-lint] Error 1
```

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

no linter issue from ci pipeline

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by codegold79** [comment]
I went ahead and gave this issue a go at it. Hopefully, no one else wanted this. PR #1784 is up.
