### ISSUE TITLE
Differentiation TKG/TCE from TMC needed in Framework v0.11.1

### ISSUE THREAD

**Issue by AnilSankar75** [vmware-tanzu/tanzu-framework#1763]
**Bug description**
While we are working on the TCE/TKG pin mode from TMC side, we found there is no field of TCE for TMC to tell whether it is TKG or TCE. This would be a blocker for TMC STARTER in march as currently the plan is to pin this to Framework v0.11.1.
Because without the differentiation, it will be an issue from support perspective that the SRE/GSS/Engineer team to provide different support for TKG and TCE. It will introduce confusion and support effort for engineering team.
Without the ability to differentiate TCE from TKG then in the TMC API/CLI/UI a TCE set-up will display as a TKG mgmt/workload cluster. UX is bad here.
**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [X] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by navidshaikh** [comment]
Related to https://github.com/vmware-tanzu/tanzu-framework/issues/1763

Potential fix: https://github.com/vmware-tanzu/tanzu-framework/issues/1259

**Comment by navidshaikh** [comment]
The fix https://github.com/vmware-tanzu/tanzu-framework/issues/1259 can be cherry-picked for the target framework release `v0.11.2` for TMC-TCE integration.

cc: @zjs @vuil @joshrosso
