### ISSUE TITLE
Non-context aware plugin listing is broken

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/tanzu-framework#1765]
**Bug description**

There are a few spots in the code that have not been updated for the context aware plugin handling. One of those is the `tanzu generate-all-docs` command. Running this command removes all references to subcommands from the generated CLI docs because it doesn't find any plugins.

The places in the code where this had previously been called that are still working have been updated to have something like:

```go
if config.IsFeatureActivated(config.FeatureContextAwareCLIForPlugins) {
		currentServerName := ""

		server, err := config.GetCurrentServer()
		if err == nil && server != nil {
			currentServerName = server.Name
		}

		serverPlugin, standalonePlugins, err := pluginmanager.InstalledPlugins(currentServerName)
		if err != nil {
			return nil, fmt.Errorf("find installed plugins: %w", err)
		}

		//nolint:gocritic
		p := append(serverPlugin, standalonePlugins...)
		for i := range p {
			plugins = append(plugins, &p[i])
		}
	} else {
		plugins, err = cli.ListPlugins()
		if err != nil {
			return nil, fmt.Errorf("find available plugins: %w", err)
		}
	}
```

But other places, like the generate-all-docs code, just call `ListPlugins` to get the set of installed plugins. That fails to find any because it looks like the plugin cache has been changed from being `~/.local/share/tanzu-cli/[set of binaries]` to be `~/.local/share/tanzu-cli/[plugin_name]/[version_named_binary]`.

The `ListPlugins` code explicitly checks if the first level under `~/.local/share/tanzu-cli/` is a directory, and if so ignores it and continues:

https://github.com/vmware-tanzu/tanzu-framework/blob/3ad462fa5fa60a336153442fbda17047d53d1ac1/pkg/v1/cli/catalog.go#L244

Since it appears this can now contain multiple versions per plugin directory, special handling would need to be added to look for the most recent binary version.

Some of the places where there is no conditional handling for context aware plugins:

https://github.com/vmware-tanzu/tanzu-framework/blob/7120a043b0c738f376810591037430ed6a0c8949/cmd/cli/plugin-admin/test/main.go#L39
https://github.com/vmware-tanzu/tanzu-framework/blob/7120a043b0c738f376810591037430ed6a0c8949/pkg/v1/cli/command/core/doc.go#L42
https://github.com/vmware-tanzu/tanzu-framework/blob/7120a043b0c738f376810591037430ed6a0c8949/pkg/v1/cli/catalog.go#L552
https://github.com/vmware-tanzu/tanzu-framework/blob/7120a043b0c738f376810591037430ed6a0c8949/pkg/v1/cli/command/core/config.go#L235
https://github.com/vmware-tanzu/tanzu-framework/blob/7120a043b0c738f376810591037430ed6a0c8949/pkg/v1/cli/command/core/plugin_manager.go#L106
https://github.com/vmware-tanzu/tanzu-framework/blob/7120a043b0c738f376810591037430ed6a0c8949/pkg/v1/cli/command/core/update.go#L44

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [X] CLI
- [X] Docs
- [ ] IAM
- [ ] Installation
- [X] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

Non-context aware plugins get returned for any instance of `ListPlugins` and that `tanzu generate-all-docs` generates the docs for all CLI commands.

**Comment by stmcginnis** [comment]
Hey @anujc25 - I think you worked on a lot of the context aware bits. Could you take a look at this?

**Comment by chandrareddyp** [comment]
This Issue has two parts:
1. The `tanzu generate-all-docs` command is not working as expected, this is fixed in  https://github.com/vmware-tanzu/tanzu-framework/pull/3192 
2. The API `cli.ListPlugins()`  is deprecated, it should be replaced with a context-aware plugin list, and also needs to remove feature flag` context-aware-cli-for-plugins`, for this created new issue https://github.com/vmware-tanzu/tanzu-framework/issues/3224

We have addressed all issues in this bug, hence closing this one.
