### ISSUE TITLE
As the maintainer of a custom CAPI infrastructure provider, I want to know if my implementation is compatible with TCE (because it passes some set of test cases)

### ISSUE THREAD

**Issue by jdef** [vmware-tanzu/tanzu-framework#1779]
## Feature Request

A set of tests, test cases, or a testing framework that helps me understand if my custom CAPI infra provider implementation is compatible w/ TCE.

## Describe alternatives you've considered

N/A

## Additional context

vmware-tanzu/community-edition#2513

**Comment by codegold79** [comment]
I left a comment in #1277 that implementations of CAPI should be tested against TCE by Framework. I'll close this issue but it can be re-opened if #1277 does not include such testing in its scope.
