### ISSUE TITLE
Remove packages/{management,standalone}/ directories and move their contents to packages/ directory

### ISSUE THREAD

**Issue by codegold79** [vmware-tanzu/tanzu-framework#1782]
(This is used to request new product features)

**Describe the feature request**

Remove `packages/{management,standalone}` directories and move their contents to the parent, `packages` directory. The following will break with the change and will need to be updated to work with the new structure:

- Makefile
- hack/packages/scripts/create-package.sh
- hack/packages/package-tools/cmd/package-bundle-generate.go
- hack/packages/package-tools/cmd/package-bundle-push.go
- hack/packages/package-tools/cmd/repo-bundle-generate.go
- hack/packages/package-tools/cmd/repo-bundle-push.go
- hack/packages/package-tools/cmd/vendir-sync.go

**Describe alternatives you've considered**

None

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

Carvel users expect package bundles to be in the packages directory, and not in an intermediary directory.

Currently, the structure for the `featuregates` package bundle is `packages/management/featuregates/bundle/`. However, this is unexpected. The expectation is `packages/featuregates/bundle/`. This is the reason for the directory structure change.

To avoid git merge conflicts, I'm going to wait for PR #1512  to be merged before I create a PR to fix this issue.

/cc: @yharish991

**Comment by yharish991** [comment]
changes need to be made in this file as well hack/packages/package-tools/cmd/vendir-sync.go
