### ISSUE TITLE
Add a warning prompt in CLI before users upgrade cluster related to core package valuesFrom customization

### ISSUE THREAD

**Issue by blc1996** [vmware-tanzu/tanzu-framework#1807]
**Describe the feature request**
Add a warning prompt in CLI before cluster upgrade. 

As we will keep all the user customization in ClusterBootstrap related to valuesFrom of core packages. Need to add a warning prompt in CLI before cluster upgrade, telling the user to make sure the compatibility if there is any customization in valuesFrom of packages

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

**Comment by vijaykatam** [comment]
Cluster upgrade is triggered from the API as well so I am not sure how this helps as CLI warning only covers a subset of clients. A scalable approach would be webhook validations that reject changes that would result in unpredictable behavior.

**Comment by blc1996** [comment]
> Cluster upgrade is triggered from the API as well so I am not sure how this helps as CLI warning only covers a subset of clients. A scalable approach would be webhook validations that reject changes that would result in unpredictable behavior.

This comes back to our previous discussion that whether we allow users to change from providerRef to SecretRef/Inline in core and additional packages. My current implementation for upgrade and webhook is to allow users to do such customizations. This sounds like users decide to break the glass and they are responsible for the `valuesFrom` that the provided.

**Comment by vuil** [comment]
@shyaamsn please assign as appropriate after the details are sorted out, as it is still unclear if there is a ux change to be made.

**Comment by vijaykatam** [comment]
Discussed with @blc1996 that is better enforced via the API in a webhook.

**Comment by blc1996** [comment]
For MVP, we are not going to allow users to change config from providerRef to secretRef/Inline. It will be enforced by webhook.
Closing this issue.
