### ISSUE TITLE
Rename CPIConfig CRD to VsphereCPIConfig

### ISSUE THREAD

**Issue by vijaykatam** [vmware-tanzu/tanzu-framework#1814]
**Describe the feature request**
The CRD needs to be renamed to VsphereCPIConfig so that when we get out of tree cloud providers for AWS and Azure the naming convention is specific.

**Affected product area (please put an X in all that apply)**

- [x] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

**Comment by HanFa** [comment]
This issue can be closed with https://github.com/vmware-tanzu/tanzu-framework/pull/1838.
