### ISSUE TITLE
Addons-controller enable metrics and profile memory and cpu usage

### ISSUE THREAD

**Issue by shivaani0505** [vmware-tanzu/tanzu-framework#1837]
We are adding a bunch of controllers to manage addons with unified TKG. The status controller is going to add a remote watch on clusters for packages being managed by clusterbootstrap. We should enable metrics, collect stats to check for memory leaks etc

1. Enable metrics https://book.kubebuilder.io/reference/metrics.html
~~2. Scale test - ask for test bed from Beijing team to test 512 clusters~~
~~3. Watch memory and cpu usage to check for leaks or cpu spikes~~

**Comment by vijaykatam** [comment]
Update scope to just enable metrics and verify that they are showing up.
