### ISSUE TITLE
Package upgrade on cluster version change

### ISSUE THREAD

**Issue by vijaykatam** [vmware-tanzu/tanzu-framework#1850]
This is a follow up to https://github.com/vmware-tanzu/tanzu-framework/pull/1713. Packages managed by ClusterBootstrap must be updated with new versions and configs when status.resolvedTKR is different from TKR label on a cluster. 

1. CLI/other clients will set paused to true when setting a new version in KCP
2. TKR controller will label the cluster with version corresponding to KCP.
3. ClusterBootstrap controller must roll out package upgrades with the following requirements

   a. Ensure packages have node selector with new TKR. (Assume TKR controller has already labeled     nodes with TKR version
   b. Ensure deployment strategy is RollingUpdate
   c. Ensure daemonset strategy is OnDelete. In prev investigation we found kapp-controller gets stuck on daemonset. Investigate and log upstream issue if needed.

**Comment by blc1996** [comment]
Add to Vijay's points:
* daemonset and deployment strategies are enforced by default in packages, no extra actions need to be taken in the ClusterBootstrap controller side
* Potential race condition for setting cluster pause label (Need investigation)

**Comment by blc1996** [comment]
https://github.com/vmware-tanzu/tanzu-framework/pull/1920 is still pending node label

**Comment by blc1996** [comment]
https://github.com/vmware-tanzu/tanzu-framework/pull/1920 is ready to be reviewed
