### ISSUE TITLE
Antrea config controller needs to read some cluster varirables

### ISSUE THREAD

**Issue by blc1996** [vmware-tanzu/tanzu-framework#1855]
(This is used to request new product features)

**Describe the feature request**
Antrea config controller needs to read some cluster varirables and put them in the right place when generating Antrea config data value secret
https://github.com/vmware-tanzu/tanzu-framework/blob/main/pkg/v1/providers/config_default.yaml#L598-L605
https://github.com/vmware-tanzu/tanzu-framework/blob/main/addons/controllers/antrea/antreaconfig_util.go#L67-L81
```
#! ---------------------------------------------------------------------
#! Antrea CNI configuration
#! ---------------------------------------------------------------------
ANTREA_NO_SNAT: false
ANTREA_TRAFFIC_ENCAP_MODE: "encap"
ANTREA_PROXY: true
ANTREA_ENDPOINTSLICE: true
ANTREA_POLICY: true
ANTREA_NODEPORTLOCAL: false
ANTREA_TRACEFLOW: true
ANTREA_DISABLE_UDP_TUNNEL_OFFLOAD: false
```

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

**Comment by shyaamsn** [comment]
@blc1996 Please close this issue with appropriate comments if this is not needed.

**Comment by blc1996** [comment]
Closing this issue because we decide these configurations happen at day 2, so they can be just set as default values on cluster creation.
