### ISSUE TITLE
Add Some Documentations for Addon Controllers

### ISSUE THREAD

**Issue by edwardbadboy** [vmware-tanzu/tanzu-framework#1897]
**Bug description**

Hi, I'm Zhengsheng Zhou from Antrea community. I see there is an [Antrea addon controller](https://github.com/vmware-tanzu/tanzu-framework/tree/main/addons/controllers/antrea) in tanzu framework. I'm learning the whole addon controller framework and maybe later the Antrea community can be involved in Antrea addon controller improvement.

Is there document for the addon controllers? Maybe put a README.md in addons/controllers/ for a summary and put some links in it? Thanks a lot!

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Comment by vijaykatam** [comment]
Done as part of https://github.com/vmware-tanzu/tanzu-framework/pull/2412
