### ISSUE TITLE
Tanzu plugin install output message content is incorrect

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/tanzu-framework#2041]
**Bug description**
When doing a `tanzu cli plugin install --local cli all`, it returns successfully installed 'all' plugin rather than successfully installed all plugins.
Current UX:
```
tanzu plugin install --local cli all

Installing plugin 'package:v0.11.1'
Installing plugin 'secret:v0.11.1'
Installing plugin 'apps:v0.5.0'
Installing plugin 'accelerator:v1.1.0'
Installing plugin 'services:v0.2.0-rc.1'
✔  successfully installed 'all' plugin
```

The message looks like it's been implemented for use with a single plugin installation per command invokation.
Because there's an option to install multiple plugins through the use of the 'all' value, the success message should be conditionally formatted differently for that scenario. 
**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [X] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [X] Plugin
- [ ] Security
- [ ] Test and Release
- [X] User Experience

**Expected behavior**
```
tanzu plugin install --local cli all

Installing plugin 'package:v0.11.1'
Installing plugin 'secret:v0.11.1'
Installing plugin 'apps:v0.5.0'
Installing plugin 'accelerator:v1.1.0'
Installing plugin 'services:v0.2.0-rc.1'
✔  successfully installed all plugins
```

**Steps to reproduce the bug**
This assumes the Tanzu CLI core is already installed...
1. Log in to [TanzuNet](https://login.run.pivotal.io/login)
2. Go to [the TAP product page's Tanzu CLI tile](https://network.pivotal.io/products/tanzu-application-platform/#/releases/1077042/file_groups/7867) and download the bundle for your OS
3. unzip the the downloaded bundle
4. run the plugin install command
  * `tanzu plugin install --local cli all`
5. notice the output from the install command - it implies a plugin named 'all' was installed which is inaccurate. 

**Version** (include the SHA if the version is not obvious)
This probably applies to any version, but here's what I've got currently:
```
tanzu version
version: v0.11.2
buildDate: 2022-03-17
sha: 9f16f375
```

**Environment where the bug was observed (cloud, OS, etc)**
haven't verified, but I assume this issue applies to all OS binaries of the CLI core.

**Comment by mpanchajanya** [comment]
PR merged
