### ISSUE TITLE
When generating cni's data values secret, the addon controller should control the values format to follow the package schemas

### ISSUE THREAD

**Issue by 12345lcr** [vmware-tanzu/tanzu-framework#2058]
**Background**
* The cni packages began to add schema in packages to restrict the input values' fields to be exact format as desired. For example [Antrea schema](https://github.com/vmware-tanzu/community-edition/blob/main/addons/packages/antrea/1.2.3/bundle/config/schema.yaml) and [Calico schema](https://github.com/vmware-tanzu/community-edition/blob/main/addons/packages/calico/3.19.1/bundle/config/schema.yaml)

* For backward compatibility, we kept image info in calico addon secret for old releases to consume. 
https://github.com/vmware-tanzu/tanzu-framework/blob/d50109c63e29c5b5b74f8da03d2aa61c1b537bbf/pkg/v1/providers/ytt/02_addons/cni/calico/calico_addon_data.lib.yaml#L16-L30
also in antrea
https://github.com/vmware-tanzu/tanzu-framework/blob/d50109c63e29c5b5b74f8da03d2aa61c1b537bbf/pkg/v1/providers/ytt/02_addons/cni/antrea/antrea_addon_data.lib.yaml#L69-L74

* The addon controller copies all the data from addon secret to generate the corresponding data values secret without checking the content. This means the invalid image info got copied to data values secret until now. 
https://github.com/vmware-tanzu/tanzu-framework/blob/d50109c63e29c5b5b74f8da03d2aa61c1b537bbf/addons/controllers/addon_reconcilers.go#L192-L209
Once we adopt cni packages with schema, this kind of data values will not pass the validation.

* Even if we removed this image info in calico addon secret, it will only solve the problem of users who create a brand new cluster. For users who upgrade to the newer version, afaik `by current design the upgrade process won't touch the existing addon secret`.

**Describe the feature request**
One proposal from my thought is to let addon controller controls the schema of the data values secret, since by design the cni version is coupled with the tanzu-framework(including addon controller) version.

Which means addon controller reconciles the existing addon secret, and not only to copy the content to the corresponding data values secret, but also `examine and modify the format of the content to meet the corresponding version's cni package schema`. This will solve the compatibility and schema problem inside the addon controller, and cleanup the invalid configurations in data values secret.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [x] Test and Release
- [x] User Experience

**Additional context**
Further more, I think we should make standards for 1. how long we should keep backward compatibility workarounds. 2. How to cleanup the the invalid configurations from old release.

**Comment by jayunit100** [comment]
lets do it ! this sounds like we need it for backward compatibility

**Comment by 12345lcr** [comment]
I have draft a pr to demonstrate the ideas. Feel free to take a look.

**Comment by 12345lcr** [comment]
After discussed with @vijaykatam and @shyaamsn , we decide to add image field to the package schema instead for backwards compatibility. I am closing this.
