### ISSUE TITLE
Pods need to work with TKGS pod security policies

### ISSUE THREAD

**Issue by vijaykatam** [vmware-tanzu/tanzu-framework#2166]
TKGS clusters are created with admission plugin PodSecurityPolicy which restricts which pods can be created on workload cluster.

1. Need default PSP policy created on workload clusters for addons to come up
2. All addon packages need to specify a pre-existing pod security policy or create one.

**Comment by shivaani0505** [comment]
Closing this one and changes are tracked as per Umbrella issue : https://github.com/vmware-tanzu/tkg-devel/issues/310
