### ISSUE TITLE
Plumb Antrea CLI addon configs to AntreaConfig API

### ISSUE THREAD

**Issue by shyaamsn** [vmware-tanzu/tanzu-framework#2369]
CLI has legacy addon configs like ANTREA_TRAFFIC_ENCAP_MODE that is used to create an addon secret. In new Addons APIs since we are using ClusterBootStrap and AddonConfig API we need to plumb the legacy addon configs to new APIs.

Create ClusterBootstrap and AddonConfig API overalys.

**Comment by shivaani0505** [comment]
Completed via #2717
