### ISSUE TITLE
Plumb Calico CLI addon configs to CalicoConfig API

### ISSUE THREAD

**Issue by shyaamsn** [vmware-tanzu/tanzu-framework#2370]
CLI has legacy addon configs like ANTREA_TRAFFIC_ENCAP_MODE that is used to create an addon secret. In new Addons APIs since we are using ClusterBootStrap and AddonConfig API we need to plumb the legacy addon configs to new APIs.

Create ClusterBootstrap and AddonConfig API overalys.

**Comment by 12345lcr** [comment]
Hi @shyaamsn , the calico 3.22.1 bump just finished and I am about to update the new 3.22.1 package value fields to the CalicoConfig. Is this issue to track this? Or it is referring other stuff?

**Comment by shivaani0505** [comment]
Completed via #2717
