### ISSUE TITLE
Go modules for apis/cni and apis/cpi breaks the controller-gen logic

### ISSUE THREAD

**Issue by 12345lcr** [vmware-tanzu/tanzu-framework#2398]
**Bug description**
https://github.com/vmware-tanzu/tanzu-framework/commit/8d668eb8b0963e54e841a59e5d04b7b2c38fbeb8
After the go modules are injected in apis, the `make manifests` can no longer generate the CRD.

**Affected product area (please put an X in all that apply)**

- [x] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [x] Test and Release
- [ ] User Experience

**Expected behavior**
The `make manifests` can generate CRDs.

**Steps to reproduce the bug**
1. Delete all in `config/crd/bases`
2. Run `make manifests`
3. All CRDs are added back except antrea, calico and cpi.
4. Remove the go.mod and go.sum in `apis/cni` and `apis/cpi`, run `make manifests` again, the missing CRDs are added back.

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**
MacOS

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by stmcginnis** [comment]
May need to do something like this: https://github.com/kubernetes-sigs/cluster-api/pull/4442
