### ISSUE TITLE
Code coverage reports integration

### ISSUE THREAD

**Issue by vijaykatam** [vmware-tanzu/tanzu-framework#2408]
(This is used to request new product features)

**Describe the feature request** 
We need integration with code coverage tools to show trends and historical test coverage in tanzu-framework so that we can use this as a measure of quality for the codebase.

1. Runs for each PR and commit
2. Gates PR
3. Summary reports.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [x] Test and Release
- [ ] User Experience

**Additional context**

**Comment by vuil** [comment]
It's a little hard to tell until we see it in action, but we probably want to update some developer docs to explain some of this integration, how much of the coverage data is accessible, etc. I may revisit this once the basic integration is in place.
