### ISSUE TITLE
ClusterBootstrap upgrade after user's initial customization

### ISSUE THREAD

**Issue by maralavi** [vmware-tanzu/tanzu-framework#2429]
**Bug description**

For the case where the user had initially provided a customized ClusterBootstrap resource and specified Calico as CNI, [this line in the code](https://github.com/vmware-tanzu/tanzu-framework/blob/14e33df6241f2b79428c1fcfaabd094dad79d159/addons/controllers/clusterbootstrap_controller.go#L470
) should not always copy from the ClusterBootstrapTemplate and instead we might need to have an annotation or label in the ClusterBootstrap object for when the addon was user-customized and if that wasn’t present, then fall back to read from  the template 

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [X] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Comment by shyaamsn** [comment]
@vijaykatam Please provide your inputs on this. Thanks

**Comment by vijaykatam** [comment]
Update should fetch the new packageRef from TanzuKubernetesRelease.spec.bootstrapPackages by searching with the first token of the package name (`calico`, `antrea`).
