### ISSUE TITLE
TC02: Able to upgrade CC Guest cluster on supervisor and verify if all addons are successfully upgraded

### ISSUE THREAD

**Issue by shivaani0505** [vmware-tanzu/tanzu-framework#2450]
Area: Addons Upgrade (Guest cluster)

**Comment by adduarte** [comment]
Test overview: 
- Testebed deployed with a management cluster
- Deploy classy cluster (class based). 
- Check addon resources
- Upgrade classy cluster to next available TKR
- Check addon resources
- Delete classy cluster
- Verify classy cluster resources have been deleted.
