### ISSUE TITLE
UTKG Addons manager needs to only process TKRs which do NOT have "run.tanzu.vmware.com/legacy-tkr" label

### ISSUE THREAD

**Issue by maralavi** [vmware-tanzu/tanzu-framework#2546]
**Bug description**
Currently, based on https://github.com/vmware-tanzu/tanzu-framework/issues/1674, utkg addons controller only processes clusters with label run.tanzu.vmware.com/tkr. However, additionally we need to also check that the related TKR does *not* have label "run.tanzu.vmware.com/legacy-tkr"

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [X] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by vijaykatam** [comment]
The legacy tkr will not have a CBT object associated with it. Instead of checking for another lablel on a TKR object lets emit info logs for missing CBT's instead of error.
