### ISSUE TITLE
Packages should vendir CRD files locally instead of duplicating

### ISSUE THREAD

**Issue by rajathagasthya** [vmware-tanzu/tanzu-framework#2679]
**Describe the feature request**

Some packages duplicate CRD files from `config/crd/bases` in their package manifests (examples [1](https://github.com/vmware-tanzu/tanzu-framework/blob/main/packages/featuregates/bundle/config/upstream/feature-crd.yaml), [2](https://github.com/vmware-tanzu/tanzu-framework/blob/main/packages/featuregates/bundle/config/upstream/featuregate-crd.yaml), [3](https://github.com/vmware-tanzu/tanzu-framework/blob/main/packages/cliplugins/bundle/config/cliplugin-crd.yaml)). These files should be `vendir`ed to ensure any updates to CRDs (generally due to updated `controller-tools`) reflects in the packages immediate and avoids lagging behind. An example of doing that is shown [here](url).

Additionally, this needs a Makefile check to make sure `vendir` is run regularly i.e. run `make package-vendir-sync` and verify there is no diff.

**Describe alternatives you've considered**

Continue to duplicate and risk CRDs being out of sync.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

**Comment by rajathagasthya** [comment]
@anujc25 I noticed cliplugins package(s) do this as well. So it would be good to clean it up whenever you get a chance.

**Comment by Vandy-P** [comment]
Hi @rajathagasthya, example link mention in issue is not working, please can you check .

**Comment by rajathagasthya** [comment]
@Vandy-P Sorry for the invalid link! Now I don't remember what link I was trying to refer to :) Hopefully, the WIP PR is enough to go on.
