### ISSUE TITLE
Cannot build cliplugins component as part of `make docker-all` or `package-push-bundles-repo` targets

### ISSUE THREAD

**Issue by randomvariable** [vmware-tanzu/tanzu-framework#2810]
**Bug description**

Attempting to follow [dev-workflow](https://github.com/vmware-tanzu/tanzu-framework/blob/main/docs/packages/dev-workflow.md) doesn't seem to work unless `COMPONENTS` is overriden to exclude `cliplugins` because of the following error:

```shell
> make docker-all
 iad.ocir.io/odx-mockcustomer/tanzu-cli-plugins/telemetry-darwin-amd64:latest
2022/07/01 10:36:18 image "tanzu-cli-plugins/telemetry-darwin-amd64:latest" not found in kbld config
exit status 1
make[2]: *** [Makefile:46: kbld-image-replace-telemetry_darwin-amd64_standalone-plugins] Error 1
make[1]: *** [Makefile:79: kbld-image-replace] Error 2
make[1]: Leaving directory '/home/ubuntu/go/src/github.com/vmware-tanzu/tanzu-framework/cliplugins'
make: *** [Makefile:740: cliplugins] Error 2
```

Additionally, excluding cliplugins from the COMPONENTS isn't documented anywhere, but does seem to be floating around in folk knowledge. Do I need it? The README for the component suggests I actually do:

> This package provides the `CLIPlugin` CRD that defines the CLIPlugin resource which is used to define CLIPlugins used by the Tanzu CLI when talking to a management cluster. This is a required package that needs to be installed on each management cluster so that the Tanzu CLI can understand the recommended set of plugins to use when talking to the cluster.

Even if I exclude it from the compoennts, I still then can't use the `package-push-bundles-repo` target:

```shell
Error: couldn't generate imgpkg lock output file: couldn't generate imgpkg lock output file: couldn't run kbld command to generate imgpkg lock output file: kbld: Error: Validating config/ (kbld.k14s.io/v1alpha1) cluster:
  Validating Overrides[0]:
    Expected NewImage to be non-empty

Usage:
  package-tooling package-bundle generate [flags]

Flags:
      --all                  Generate all package bundles in a repository
  -h, --help                 help for generate
      --registry string      OCI registry where the package bundle image needs to be stored
      --repository string    Package repository of the package bundle being created
      --sub-version string   Package bundle subversion
      --thick                Include thick tarball(s) in package bundle(s)
      --version string       Package bundle version

exit status 1
make: *** [Makefile:767: package-bundles] Error 1
```

Additionally, these build tools print out the errors from the underlying carvel tools, but don't tell us what command was actually being run.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [ ] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [x ] Test and Release
- [ ] User Experience

**Expected behavior**

Dev workflow works.

**Steps to reproduce the bug**

Run `make docker-all` on a clean checkout.

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

Linux &
MacOS

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by yharish991** [comment]
@randomvariable telemetry plugin code was merged yesterday, so you might want to build the cli again and do `make docker-all`, I just ran `make docker-all` to verify things and it works fine..
