### ISSUE TITLE
Expose ability to passthrough PCI devices in vSphere 7+ from CAPV v1.3.0 (TBD)

### ISSUE THREAD

**Issue by randomvariable** [vmware-tanzu/tanzu-framework#2828]
**Describe the feature request**

The next release of Cluster API Provider vSphere will include support for mapping PCI devices into [VMs using passthrough support (aka vSphere DirectPath)](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1264). We want to light this up feature in TKG, both pre and post ClusterClass.

We additionally require allowing users to change the machine deployment rollout strategy because they might not have sufficient hardware to do an upgrade otherwise.

Required UX:

Add the following variables to existing vSphere cluster plans:

### `VSPHERE_WORKER_PCI_DEVICES` and `VSPHERE_CONTROL_PLANE_PCI_DEVICES`

* Type: String
* Default: ""
* Variable to be modified:
  - `VSPHERE_WORKER_PCI_DEVICES`:
    - Modify all vSphereMachineTemplates matching `"${ CLUSTER_NAME }-worker"`
    - Modifies `spec.template.spec.pciDevices` as below
  - `VSPHERE_CONTROL_PLANE_PCI_DEVICES`:
    - Modify all vSphereMachineTemplates matching `"${ CLUSTER_NAME }-control-plane"`
    - Modifies `spec.template.spec.pciDevices` as below

If "", do not set. If value other than "", then do the following:

```psuedocode
# This is just pseudocode. Needs to be in YTT (Starlark).

devices = []
kvs = string.split(value, ",")
if len(kvs) == 0, return nil
for each kv in kvs:
  if !VSPHERE_IGNORE_PCI_DEVICES_ALLOW_LIST && kv not in allowedPCIDevices:
     return validation error
  vendor, device = string.split(kv, ":")
  if device == nil, return validation error
  devices.append(
   {
      vendorID: vendor,
      deviceID: deviceID
   }
  )
```

E.g:

Assuming the `allowedDevices` list contains `00001:10000` and `00002:20000`, then:

`VSPHERE_WORKER_PCI_DEVICES="00001:10000,00002:20000"` should result in

```yaml
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata: cluster-worker
...
spec:
...
  template
    spec:
    ...
    pciDevices:
    - vendorID: 00001
      deviceID: 10000   
    - vendorID: 00002
      deviceID: 20000 
```

The following should return an "invalid format" error:
* `VSPHERE_WORKER_PCI_DEVICES="00001:10000;00002:20000"`
* `VSPHERE_WORKER_PCI_DEVICES="00001:10000,00002;20000"`
* `VSPHERE_WORKER_PCI_DEVICES="0000110000"`

The following should return a "One or more PCI devices not validated. Set VSPHERE_IGNORE_PCI_DEVICES_ALLOW_LIST to true to override":

* `VSPHERE_WORKER_PCI_DEVICES="00001:10000;00003:30000"`
* `VSPHERE_WORKER_PCI_DEVICES="00003:30000"`

### `WORKER_ROLLOUT_STRATEGY`

* Type: String
* Enum: `OnDelete` or `RollingUpdate`. Fail validation if other value provided.
* Default: `RollingUpdate`
* Modifies: Any `MachineDeployment.spec.strategy.type` to the specified value.

This setting is generic across all providers, so does not have the vSphere prefix

### `VSPHERE_CONTROL_PLANE_CUSTOM_VMX_KEYS` and `VSPHERE_WORKER_CUSTOM_VMX_KEYS`

* Type: String
* Default: ""

If set, deconstructs comma-separated key value pairs, e.g.

`VSPHERE_CUSTOM_VMX_KEYS="pciPassthru.allowP2P=true,pciPassthru.RelaxACSforP2P=true,pciPassthru.use64bitMMIO=true,pciPassthru.64bitMMIOSizeGB=512"` into a map in spec.template.spec.customVMXKeys, e.g.

```yaml
      customVMXKeys:
        pciPassthru.64bitMMIOSizeGB: "512"
```

### Stretch goal: `VSPHERE_IGNORE_PCI_DEVICES_ALLOW_LIST`

* Type: Boolean
* Default: false
* Behaviour: If set, disables the enumeration for vendor and device class in `VSPHERE_WORKER_PCI_DEVICES` and `VSPHERE_CONTROL_PLANE_PCI_DEVICES`

## Acceptance Criteria

* [vSphere templates and YTT updated to handle the logic above](https://github.com/vmware-tanzu/tanzu-framework/tree/main/pkg/v1/providers/infrastructure-vsphere)
* [ClusterGen and unit tests added where appropriate](https://github.com/vmware-tanzu/tanzu-framework/tree/main/pkg/v1/providers/tests)
* [TKG Client library for vSphere](https://github.com/vmware-tanzu/tanzu-framework/blob/main/pkg/v1/tkg/tkgconfigproviders/vsphere.go) updated to also include the variables
* Validation errors given to end user when the input is invalid

## Reviewers

For Cluster API vSphere correctness, @yastij and @randomvariable  will be reviewers
For Tanzu Framework correctness, @anujc25 

**Affected product area (please put an X in all that apply)**

- [X] APIs
- [X] CLI
- [X] Installation
- [X] Plugin
- [X] User Experience

**Additional context**

**Comment by jayunit100** [comment]
```
also, IF_GPU_ENABLED
pciPassthru.allowP2P = true
pciPassthru.RelaxACSforP2P = true
pciPassthru.use64bitMMIO TRUE
pciPassthru.64bitMMIOSizeGB 512
```

**Comment by jayunit100** [comment]
(updated above comment, removed if_gpu..)
