### ISSUE TITLE
featuregate api failing for non administrator user

### ISSUE THREAD

**Issue by chandrareddyp** [vmware-tanzu/tanzu-framework#2945]
**Bug description**
For TKGS non-administrator users, the CLI command ` tanzu cluster list -n ns01` is failing with the below error:
```
Error: error while checking feature 'vmware-system-tkg-clusterclass' status in namespace 'vmware-system-tkg': failed to get namespaces from NamespaceSelector: namespaces is forbidden: User "janedoe@example.com" cannot list resource "namespaces" in API group "" at the cluster scope
Error: exit status 1
```

Here are steps to reproduce:

- In the TKGS testbed, create a namespace (ns01) and a new user created(user1) and assign Edit permissions to namespace (ns01).
- Generate kubeconfig file by connecting to the TKGS cluster with kubectl vsphere login with the newly created user (user1).
- In my local system, CLI is installed, and tkgs supervisor is added as a new server (with `tanzu login` command).
- the command 'tanzu cluster list -n ns01' fails with above error

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
`tanzu cluster list `command should work
**Steps to reproduce the bug**
listed in description
**Version** (include the SHA if the version is not obvious)
➜  cli tanzu cluster version
v0.25.0-dev
**Environment where the bug was observed (cloud, OS, etc)**
Mac
**Relevant Debug Output (Logs, manifests, etc)**

**Comment by rajathagasthya** [comment]
Closing as we are tracking a larger issue around RBAC separately
