### ISSUE TITLE
Missing newline on tanzu builder cli add-plugin command

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu/tanzu-framework#300]
**Bug description**

Missing newline when running the `tanzu builder cli add-plugin <name>` command.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [ X ] CLI
- [ ] Docs
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ X ] User Experience

**Expected behavior**

A new line would be created after a plugin is added.

**Steps to reproduce the bug**

Run the `tanzu builder cli add-plugin <name>` command.

**Version** (include the SHA if the version is not obvious)

tanzu version
version: v1.3.1
buildDate: 2021-05-07
sha: e5c37c4

**Environment where the bug was observed (cloud, OS, etc)**

MacOS

**Relevant Debug Output (Logs, manifests, etc)**

Here is an output of the command:

```bash
sdustin-a01:operator sdustin$ tanzu builder cli add-plugin operator
? provide a description test
successfully created pluginsdustin-a01:operator sdustin$
```

**Comment by mpanchajanya** [comment]
Not Reproducible with the latest main source code. 
![Screen Shot 2022-08-04 at 12 19 13](https://user-images.githubusercontent.com/106101699/182912064-0bc90835-2ed5-479c-af68-f030650cad5c.png)
