### ISSUE TITLE
Object propagation controller propagates Cluster specific `AWSMachineTemplate` and `KubeadmConfigTemplate` resources as well

### ISSUE THREAD

**Issue by anujc25** [vmware-tanzu/tanzu-framework#3005]
**Bug description**

Object propagation controller is responsible for coping all clusterclass related resources to all the namespaces and we are providing the configuration as part of object propagation deployment.

However, controller also propagates Cluster specific `AWSMachineTemplate` and `KubeadmConfigTemplate` resources as well to all the namespaces.

We should only propagate ClusterClass owned resources to all namespaces and not Cluster owned resources.

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
Cluster specific resources should not be copied to all namespaces

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by imikushin** [comment]
I'm inclined to close this: looks like it only happens if clusters are created in `tkg-system` namespace, which users shouldn't really do.

**Comment by anujc25** [comment]
Unfortunately, There will always be a management-cluster created in `tkg-system` namespace.

Updated #3007 to propagate only clusterclass related resources to other namespaces which doesn't have `topology.cluster.x-k8s.io/owned` label.

`MachineTemplate` and `KubeadmConfigTemplate` resources that gets created by the topology controller for the clusters will include `topology.cluster.x-k8s.io/owned` label. So, We need to skip resources with this labels from coping to other namespaces.
