### ISSUE TITLE
kubeval linter not used

### ISSUE THREAD

**Issue by marckhouzam** [vmware-tanzu/tanzu-framework#3075]
**Bug description**

When running `make lint`, the tool `kubeval` is being installed but it does not seem to ever be used.
It is a bit inefficient but mostly, it prevents `make lint` from running on `darwin-arm64` because `kubeval` is not available for that architecture; therefore, `make lint` fails when trying to install `kubeval` even though the tool is not needed.

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- (x) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**

Ultimately, the goal is to have `make lint` pass on `darwin-arm64`,

**Steps to reproduce the bug**

On a Mac M1, run `make lint` and you should see:
```
make -C /Users/kmarc/git/tanzu-framework/hack/tools kubeval
mkdir -p bin
curl -sL https://github.com/instrumenta/kubeval/releases/download/0.15.0/kubeval-darwin-arm64.tar.gz | tar -xz -C /tmp/
tar: Error opening archive: Unrecognized archive format
make[1]: *** [bin/kubeval] Error 1
make: *** [/Users/kmarc/git/tanzu-framework/hack/tools/bin/kubeval] Error 2
```

**Version** (include the SHA if the version is not obvious)

`main` branch: sha 46b4f80a

It seems that the use of `kukbeval` was removed in #204, but the installation of it was not removed.

**Environment where the bug was observed (cloud, OS, etc)**

Locally on Mac M1

**Comment by marckhouzam** [comment]
I can post a PR to completely remove `kubeval` if that is the preferred solution.
Or we can start using it again?

**Comment by seemiller** [comment]
I encountered this as well. `kubeval` appears to have been abandoned, with the last PR merge in April, 2021.

**Comment by vuil** [comment]
Thanks for cleaning this up. 3088 merged. Folks can consider reopening this if kubeval use needs to be resurrected.
