### ISSUE TITLE
Plugin fails when cgo related warnings are printed

### ISSUE THREAD

**Issue by odinnordico** [vmware-tanzu/tanzu-framework#3393]
**Bug description**

As of [Xcode 14](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes) release when building a plugin ([apps cli plugin](https://github.com/vmware-tanzu/apps-cli-plugin/tree/v0.9.0)) with `CGO_ENABLED=1`, the clang is throwing up some warnings that are shown by golang linker as described in a reported issue ([54482](https://github.com/golang/go/issues/54482#issuecomment-1245534987)) causing that when the builder is parsing the plugin `info` fails due to unmarshalling error as follows:

![image](https://user-images.githubusercontent.com/2386675/190829220-549e0db6-523f-45d3-8d2d-2485ce02c76e.png)

![image](https://user-images.githubusercontent.com/2386675/190829303-f23c214c-836c-4362-bb3c-a7d4815aa53a.png)

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- (X) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- (X) Developer Experience

**Expected behavior**

The plugin is built even if warnings are thrown by external sources when there is a valid `info` output

**Steps to reproduce the bug**

- Update the Xcode tools to latest version ([14](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes))
- Build _tanzu framework_ from source with `make build-install-cli-local`
- Set the environment variable `CGO_ENABLED=1`
- Clone ([apps cli plugin](https://github.com/vmware-tanzu/apps-cli-plugin/tree/v0.9.0)) and build from source using `make install`

**Version** (include the SHA if the version is not obvious)

version: v0.25.0

**Environment where the bug was observed (cloud, OS, etc)**

OS: macOS Monterey Version 12.6
Go Version: go version go1.19 darwin/amd64
gcc --version:
  Apple clang version 14.0.0 (clang-1400.0.29.102)
  Target: x86_64-apple-darwin21.6.0
  Thread model: posix

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by randomvariable** [comment]
I believe this was fixed by https://github.com/vmware-tanzu/tanzu-framework/pull/3909/files
