### ISSUE TITLE
Plugin specific Feature-Flags should not be defined in plugin runtime library (cli/runtime)

### ISSUE THREAD

**Issue by anujc25** [vmware-tanzu/tanzu-framework#3447]
**Bug description**

Currently, we are defining all available feature-flag as part of core-cli integration library which includes plugin specific feature-flags. Reference: https://github.com/vmware-tanzu/tanzu-framework/blob/main/cli/runtime/config/featureflags.go#L24-L58

Core CLI integration library should not specify plugin specific feature-flags and it should only define core-cli specific feature-flags.
Plugins specific feature-flag should be defined in plugin implementation.

Proposal is to have each plugin define its own feature-flags and use `postInstallHook` to configure the default feature-flag values to the ClientConfig if needed.

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- (x) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- (x) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
Remove plugin specific feature-flag definition from core-cli integration library.

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by vuil** [comment]
I think requiring the initialization of feature flags in the postinstall hook may be a bit too inflexible unless we can guarantee we will never need to do it except when a plugin is being installed/upgraded.
