### ISSUE TITLE
metrics-server for management cluster takes ownership kube-system namespace

### ISSUE THREAD

**Issue by adduarte** [vmware-tanzu/tanzu-framework#3595]
**Bug description**
The configuration for the metrics-server which is deployed to the administration server uses the default
("createNamespace: true") when it is to be deployed on the "kube-system" namespace. 
Using "createNamespace: true" causes kapp-controller to take ownership of the namespace and assign it to the metrics-server app. 
The result is that if a admin user makes any changes to the "kube-system" namespace, they will be reverted back when metric-server app is reconciled by addons-manager.  It also adds kapp.k14s.io annotations and labels to the namespace which can interfere with control-plane operations. For example, when the metric-server app is deleted, the system will try to delete kube-system namespace which is not allowed, resulting in a problem. 

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( x) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
changes to the kube-system namespace added by the user should not be over-written when the metric-server app is reconciled. 

**Steps to reproduce the bug**
deploy a cluster 
1. kubectl label namespace kube-system custom=label
2. wait a few minutes
3. kubectl get ns --show-labels kube-system
after a few minutes the "custom: label" label will disappear. 
any changes made to the kube-system namespace will disappear once metric-server is reconciled. 

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by yharish991** [comment]
@adduarte can i assign this issue to you?

**Comment by adduarte** [comment]
This is fixed by https://github.com/vmware-tanzu/tanzu-framework/pull/3596
