### ISSUE TITLE
Missing fields on AntreaConfig CRD

### ISSUE THREAD

**Issue by knabben** [vmware-tanzu/tanzu-framework#3712]
**Bug description**
AntreaConfig CRD mismatches clusterbootstrap.yaml template.

**Affected product area (please put an X in all that apply)**

- (x) APIs
- (x) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
To have both sides match, AntreConfig and clusterbootstrap template

**Comment by codegold79** [comment]
Thanks @knabben for filing and taking on this issue with #3715. I've assigned you for this issue.
