### ISSUE TITLE
TKGm 1.6 cannot be deployed in air-gapped environments due to an issue in `gen-publish-images-totar.sh`

### ISSUE THREAD

**Issue by itaytalmi** [vmware-tanzu/tanzu-framework#3757]
**Bug description**

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- ( X ) CLI
- ( ) Docs
- ( ) IAM
- ( X ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**

I am following the [official documentation](https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.6/vmware-tanzu-kubernetes-grid-16/GUID-mgmt-clusters-image-copy-airgapped.html) to deploy TKGm 1.6 in an air-gapped environment.

In step 2 (`Generate the images-to-tar-list File`), the `gen-publish-images-totar.sh` [script](https://raw.githubusercontent.com/vmware-tanzu/tanzu-framework/e3de5b1557d9879dc814d771f431ce8945681c48/hack/gen-publish-images-fromtar.sh) from upstream Tanzu Framework is used to generate a list of bundles and images that should be pulled using `imgpkg copy`, then `download-images.sh` is used to pull the images based on the generated `images-to-tar-list` file.

In TKGm 1.6, that step is broken due to an issue in the `gen-publish-images-totar.sh` file. `download-images.sh` starts running, downloads hundreds of images, and after about 2 hours it fails with this error message:

```text
running imgpkg copy -i projects.registry.vmware.com/tkg/packages/capabilities:v0.25.0-23-g6288c751_vmware.1 --to-tar packages-capabilities-v0.25.0-23-g6288c751_vmware.1.tar

imgpkg: Error: Expected bundle flag when copying a bundle (hint: Use -b instead of -i for bundles)

Download failed. Retrying....

imgpkg: Error: Expected bundle flag when copying a bundle (hint: Use -b instead of -i for bundles)

Download failed. Retrying....
```

After investigating, this is because `capabilities:v0.25.0-23-g6288c751_vmware.1` has been added in 1.6, and it is a bundle, not an image. The hint provided by the error message is correct - `imgpkg copy` should be used with the `-b` flag in this case, rather than `-i`.

My colleague @vrabbi has suggested the following fix:

In line 113 here:
https://github.com/vmware-tanzu/tanzu-framework/blob/main/hack/gen-publish-images-totar.sh#L113
You could change `if [ $comp = "tkg-core-packages" ]; then` to `if [ $comp = "tkg-core-packages" ] || [ $comp = "capabilities-package" ]; then`

Ideally, it would be better to have a precheck for each image/bundle and dynamically set the `-i` and `-b` flags for `imgpkg copy` accordingly. I've issued this feature request in upstream imgpkg:
https://github.com/vmware-tanzu/carvel-imgpkg/issues/446

**Steps to reproduce the bug**

Follow the official air-gapped docs:
https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.6/vmware-tanzu-kubernetes-grid-16/GUID-mgmt-clusters-image-copy-airgapped.html

My exact steps:

```bash
export TKG_IMAGE_REPO="projects.registry.vmware.com/tkg"
export TKG_BOM_IMAGE_TAG="v1.6.0"
export DOWNLOAD_TKRS="v1.23.8_vmware.2-tkg.1 v1.22.11_vmware.2-tkg.1" # Excluding v1.21.14_vmware.2-tkg.1 as I don't need it

wget https://raw.githubusercontent.com/vmware-tanzu/tanzu-framework/e3de5b1557d9879dc814d771f431ce8945681c48/hack/gen-publish-images-totar.sh
chmod +x gen-publish-images-totar.sh

./gen-publish-images-totar.sh > images-to-tar-list
cat images-to-tar-list

#! Create download-images.sh and make sure it's executable - 'chmod +x download-images.sh'

# run download-images.sh
./download-images.sh images-to-tar-list
```

**Version** (include the SHA if the version is not obvious)

```text
$ imgpkg version
imgpkg version 0.29.0

$ tanzu version
version: v0.25.0
```

**Environment where the bug was observed (cloud, OS, etc)**

Linux Ubuntu 22.04

**Relevant Debug Output (Logs, manifests, etc)**

See above.

**Comment by codegold79** [comment]
@danniel1205, I think you might be working on this issue. I've assigned it to you, but let me know it's out of scope for what you're working on.
