### ISSUE TITLE
Better feedback on tanzu CLI initialization

### ISSUE THREAD

**Issue by iancoffey** [vmware-tanzu/tanzu-framework#38]
**Describe the feature request**
On first run of tanzu CLI you get an `Initializing` message and it the initialization process might take up to some minutes, as it pulls down plugins from remote repositories. Since a user might not know what's going on, it would be ideal to provide better feedback to the user.

**Describe alternatives you've considered**
Provide a message like `Initializing. Core plugins are being downloaded (this might take some time)`

**Affected product area (please put an X in all that apply)**

[ ] APIs
[ ] Addons
[* ] CLI
[ ] Docs
[ ] Installation
[ ] Plugin
[ ] Security
[ ] Test and Release
[*] User Experience

**Additional context**

**Comment by anujc25** [comment]
This behavior should no longer exists as we do show some logs when syncing/downloading plugins.
