### ISSUE TITLE
Change the proxy setting format in CC

### ISSUE THREAD

**Issue by lubronzhan** [vmware-tanzu/tanzu-framework#3813]
**Bug description**

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- (x) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
Refactor the proxy format in CC, otherwise the cluster object annotation won't consume it
**Steps to reproduce the bug**
Cluster creation succeeded. but the annotation in cluster doesn't get correct proxy setting
**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by marckhouzam** [comment]
Fixed by #3812
