### ISSUE TITLE
ClusterClass should be the default management cluster mode

### ISSUE THREAD

**Issue by xiujuanx** [vmware-tanzu/tanzu-framework#3957]
**Describe the feature request**
Need to enable the cluster class as default mode in Glasgow. Currently legacy is set as default which needs to be replaced by cluster class. Also MC and WC is using the feature gate to control its cluster mode. we need to decouple it.
This issue is related to this [TKG issue](https://jira.eng.vmware.com/browse/TKG-14926).

**Describe alternative(s) you've considered**

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- (X) CLI
- (X) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- (X) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Additional context**

**Comment by codegold79** [comment]
It looks like @xiujuanx fixed this issue with #3956. Closing issue.
