### ISSUE TITLE
Add core addons installation status to cluster conditions

### ISSUE THREAD

**Issue by iancoffey** [vmware-tanzu/tanzu-framework#41]
(This is used to request new product features)

**Describe the feature request**
Currently, when cluster is deployed with core addons there isnt a status/condition in the cluster to look at for successful installation of these addons. Adding cluster conditions is useful for tanzu cli to scrap the status, wait for all addons installation to be completed and error out if any addons fail to be deployed

**Describe alternatives you've considered**
Look at App CR status directly. This is cumbersome and for core addons, status should be in cluster object

**Affected product area (please put an X in all that apply)**

[ ] APIs
[x] Addons
[ ] CLI
[ ] Docs
[ ] Installation
[ ] Plugin
[ ] Security
[ ] Test and Release
[ ] User Experience

**Additional context**

### Collated Context

Context from 2021-03-02 15:58:00
User: vijaykatam
As part of this change, we will need to ensure to do some scale testing to analyze memory requirements and potential leaks for the pod.

**Comment by vijaykatam** [comment]
This is not valid anymore. A new resource ClusterBootstrap has been implemented and it aggregates statuses of managed packages.
