### ISSUE TITLE
Isolated-cluster: --destination-insecure flag on the wrong command

### ISSUE THREAD

**Issue by marckhouzam** [vmware-tanzu/tanzu-framework#4150]
**Bug description**

For the new `isolated-cluster` plugin, grom what I can tell, the `--destination-insecure` flag should be for the `upload-bundle` command. However, it is instead showing on the `download-bundle` command.

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- (x) Installation
- (x) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**

The `--destination-insecure` command should be on the `upload-bundle` command.

**Steps to reproduce the bug**

Notice the presence of a `--destination-insecure` flag on the `download-bundle` command:
```
$ tanzu isolated-cluster download-bundle -h
Download images/bundle into local disk as TAR

Usage:
  tanzu isolated-cluster download-bundle [flags]

Flags:
      --destination-insecure           Trusts the server certificate without validating it (optional)
  -h, --help                           help for download-bundle
      --source-ca-certificate string   The private repository’s CA certificate  (optional)
      --source-insecure                Trusts the server certificate without validating it (optional)
      --source-repo string             OCI repo where TKG bundles or images are hosted (required) (default "projects.registry.vmware.com/tkg")
      --tkg-version string             TKG version (required)
```
and notice there is no `--destination-insecure` flag for the `upload-bundle` command

```
./isolated-cluster upload-bundle -h
Upload images to private repository.

Usage:
  tanzu isolated-cluster upload-bundle [flags]

Flags:
      --destination-ca-certificate string   The private repository’s CA certificate  (optional)
      --destination-repo string             Private OCI repository where the images should be hosted in air-gapped (required)
  -h, --help                                help for upload-bundle
      --source-directory string             Path to the directory that contains the TAR file  (required)

```

**Version** (include the SHA if the version is not obvious)

Today's main: 84cc3e591

**Environment where the bug was observed (cloud, OS, etc)**

Locally

It was an easy fix so I'll post a PR.

cc @Vandy-P

**Comment by vuil** [comment]
typo on the mention in #4152. It was related to https://github.com/vmware-tanzu/tanzu-framework/pull/4148 instead.
