### ISSUE TITLE
isolated-cluster plugin does not follow CA trust conventions

### ISSUE THREAD

**Issue by randomvariable** [vmware-tanzu/tanzu-framework#4173]
**Bug description**

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- (X) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

with the following:

```
  --source-ca-certificate
  --source-insecure
  --destination-ca-certificate string   The private repository’s CA certificate  (optional)
   --destination-insecure                Trusts the private repository’s certificate without validating it (optional)
```

the behaviour is counter to any downloader i have ever used. If the CA certificate isn't specified, then the system trust store isn't currently used. there's no file to point to for this on MacOS and Windows, which makes this unusable on those systems by any enterprise that wants to do airgapped and follow standard security practices. For Linux, the user would need to know the path to the system trust store which is different on different distributions.

I'm also not sure of the utility of the separate source-ca-certificate an destination-ca-certificate flags. Let's simply reduce to just `--ca-certificate` and `--insecure` and use the same set on either. By convention `--insecure` COULD have a `-k` as a shortflag to match other CLIs that copy curl semantics.

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by randomvariable** [comment]
This is still broken for upload-bundle.

**Comment by Vandy-P** [comment]
Hi @randomvariable  , Please check the latest changes , its resolved now.
