### ISSUE TITLE
TKR_DATA formation in tkr-resolver overrides ImageRepository for every component

### ISSUE THREAD

**Issue by rajaskakodkar** [vmware-tanzu/tanzu-framework#4178]
**Bug description**

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- (x) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
tkr-resolver takes Kubernetes spec from TKR yaml and then forms TKR_DATA. If TKR yaml provides imageRepository for a component, say kube-vip, then it should be reflected in TKR_DATA. In this case, it is overridden by customImageRepository https://github.com/vmware-tanzu/tanzu-framework/blob/main/tkr/webhook/cluster/tkr-resolver/cluster/cluster.go#L333-L349 
**Steps to reproduce the bug**
Set imageRepository for any of etcd, coredns, kube-vip or pause in TKR yaml and create a management cluster. Notice TKR_DATA created by tkr-resolver. 
**Version** (include the SHA if the version is not obvious)
v0.28.0-dev
**Environment where the bug was observed (cloud, OS, etc)**
vsphere
**Relevant Debug Output (Logs, manifests, etc)**

**Comment by imikushin** [comment]
When the cluster has `imageRepository` variable set (which is optional), this behavior **is** correct.
