### ISSUE TITLE
Review copyright headers and fix them

### ISSUE THREAD

**Issue by shyaamsn** [vmware-tanzu/tanzu-framework#4227]
**Bug description**
Copyright headers in source files are not consistent.There are files with years as 2021, 2022, 2023. Need to review them and fix them to have a consistent format

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**
Consistent copyright headers

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by rajathagasthya** [comment]
For anyone looking into this, copyright header template is in `hack/boilerplate.go.txt`.

**Comment by codegold79** [comment]
Looks liked #4225 fixes this issue.
