### ISSUE TITLE
Disable color and symbols when TTY not present

### ISSUE THREAD

**Issue by iancoffey** [vmware-tanzu/tanzu-framework#43]
(This is used to request new product features)
Add a TTY checker for the CLI to disable the use of color, symbols, animation, and emojis when TTY not present or when env var TERM=dumb is set.

Add a checker for the CLI to disable the use of color when the NO_COLOR env var is set to true.

**Describe the feature request**

Making machine-reading easier by simplifying the outputs when we can detect non-TTY action or when explicitly requested by the user. 

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] APIs
[ ] Addons
[x] CLI
[ ] Docs
[ ] Installation
[ ] Plugin
[ ] Security
[ ] Test and Release
[ ] User Experience

**Additional context**

**Comment by danfein** [comment]
Note, the init spinner animation came up as an issue with Chocolately during the beta2 bug bash. The change proposed in this issue would help unblock cli users on windows.

From @nrb 
```
The Windows Console Host doesn't do any of the TTY stuff :disappointed:

And we must use the Windows Console Host (traditional cmd.exe and Powershell) with Chocolatey, because the modern Windows Terminal doesn't support running as Admin
```

**Comment by heyjcollins** [comment]
bumping this as an important issue to pick up given the preponderance of Windows users vs. linux and mac
