### ISSUE TITLE
Use build tooling to build FeatureGates component

### ISSUE THREAD

**Issue by avi-08** [vmware-tanzu/tanzu-framework#4449]
**Describe the feature request**
This issue is to track the effort to consume [build tooling](https://github.com/vmware-tanzu/build-tooling-for-integrations) to build featuregates component.

**Describe alternative(s) you've considered**

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- (X) Test and Release
- ( ) User Experience
- (X) Developer Experience

**Additional context**

**Comment by codegold79** [comment]
Thanks @avi-08 for the update and getting that merged. Closing issue.
