### ISSUE TITLE
[Build Tooling] Docker cache gets invalidated while building unit-test-coverage image

### ISSUE THREAD

**Issue by sathyanarays** [vmware-tanzu/tanzu-framework#4465]
**Bug description**

```
test: fmt vet
	$(DOCKER) build . -f Dockerfile --target test --build-arg COMPONENT=$(COMPONENT) --build-arg GOPROXY_ARG=$(GOPROXY)
	@$(DOCKER) build . -f Dockerfile --target unit-test-coverage --build-arg COMPONENT=$(COMPONENT) --output build/$(COMPONENT)/coverage
```

The test target in `build-tooling.mk` should make use of cache for go modules across various images. Everything works expected except in building `unit-test-coverage` image; the cache gets invalidated and go modules is computed again.

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- (X) Test and Release
- ( ) User Experience
- (X) Developer Experience

**Expected behavior**
building `unit-test-coverage` image should reuse the go mod cache

**Steps to reproduce the bug**
Run `make docker-build-all -f build-tooling.mk` from the runtime core feature branch

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by codegold79** [comment]
Close issue as it looks like it was fixed with #4462.
