### ISSUE TITLE
The /tkg/Makefile does not support `generate-fakes` 

### ISSUE THREAD

**Issue by benjaminapetersen** [vmware-tanzu/tanzu-framework#4500]
**Bug description**

The /tkg/Makefile does not support `generate-fakes` yet this is necessary as the `/tkg/fakes` directory exists and was generated via the [counterfeiter](https://github.com/maxbrunsfeld/counterfeiter) mod used in the root `Makefile`.

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- ( ) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by codegold79** [comment]
Closing issue as it looks like @benjaminapetersen raised and got  #4501  merged.
