### ISSUE TITLE
Incorrect handling of version prefix when updating TKR Compatible status condition

### ISSUE THREAD

**Issue by imikushin** [vmware-tanzu/tanzu-framework#452]
We're determining if a TKR is compatible with a management cluster by looking if a _string prefix_ of management cluster TKG version is listed as an entry of `managementClusterVersions` list in BOM compatibility metadata. The code that is doing this in `UpdateTKRCompatibleCondition` method of the TKR reconciler looks like this:
```go
// TODO Fix before TKG v1.10: what if mgmtClusterVersion is "v1.10" and mgmtVersion.TKGVersion is "v1.1"?
if strings.HasPrefix(mgmtClusterVersion, mgmtVersion.TKGVersion) {
	compatibleReleases = mgmtVersion.SupportedKubernetesVersions
}
```

We do have some time, as we need to fix this before TKG v1.10

**Comment by prkalle** [comment]
Fixed with the PR :https://github.com/vmware-tanzu/tanzu-framework/pull/1139. The prefix match is changed to exact match.
