### ISSUE TITLE
Creating a management cluster led to an error about the CEIP telemetry job

### ISSUE THREAD

**Issue by zjs** [vmware-tanzu/tanzu-framework#5]
**Bug description**

When deploying a CAPD management cluster through TCE, I encountered the following error message in my logs "Failed to start CEIP telemetry job on management cluster".

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [ ] CLI
- [ ] Docs
- [x] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [x] User Experience

**Expected behavior**

As a user, I would not expect to see error messages in my logs when creating a management cluster.

**Steps to reproduce the bug**

1. Run `tanzu management-cluster create --ui`
2. Select Docker
3. Deploy with default settings

**Version** (include the SHA if the version is not obvious)

TCE v0.6.0-rc1

**Environment where the bug was observed (cloud, OS, etc)**

CAPD

**Relevant Debug Output (Logs, manifests, etc)**

```
✘ [0630 09:30:40.57152]: init.go:292] Failed to start CEIP telemetry job on management cluster: failed to parse telemetry spec yaml: open pkg/manifest/telemetry/config-docker.yaml: file does not exist
‼ [0630 09:30:40.57156]: init.go:294] To have this cluster participate in VMware CEIP:
‼ [0630 09:30:40.57178]: init.go:295] tanzu management-cluster ceip-participation set true
```

**Comment by danniel1205** [comment]
I think this PR might have fixed the issue. https://github.com/vmware-tanzu/tanzu-framework/pull/1257
@saimanoj01 , could you please help confirm ? Thhanks

**Comment by stmcginnis** [comment]
CEIP is now defaulted to off in TCE, so I think this is no longer an issue. Closing, but if we are missing something please feel free to reopen with additional details.
