### ISSUE TITLE
Use a GitHub Action to welcome new contributors 

### ISSUE THREAD

**Issue by LappleApple** [vmware-tanzu/tanzu-framework#556]
**Feature Request**
To apply a GitHub Action ([see example](https://github.com/garg3133/welcome-new-contributors)) to welcome new contributors. 

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [ ] CLI
- [ ] Docs
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**
Filed the same issue on TCE: https://github.com/vmware-tanzu/community-edition/issues/1537

**Comment by vuil** [comment]
@navidshaikh do you think you can assign this as appropriate?
