### ISSUE TITLE
Shell completion should not trigger cli initialization

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/tanzu-framework#587]
**Bug description**

After running `tanzu plugin clean` and then trying to use tab completion to complete the next command, the initialization captures the request for shell completion and causes the shell to appear frozen for several seconds.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [X] CLI
- [ ] Docs
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

The hidden cobra completion commands like `__completion` should always be invokable and return info based on known commands. It should not cause side effects on the user's machine.

**Steps to reproduce the bug**

1. install the shell completion into your current shell
2. run `tanzu plugin clean`
3. type `tanzu <tab>`

**Version** (include the SHA if the version is not obvious) 

I'm using a custom build, but that's shouldn't matter.

```
tanzu version               
version: v0.2.0
buildDate: 2021-09-09
sha: f5a87174
```

**Environment where the bug was observed (cloud, OS, etc)**

mac OS, zsh

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by stmcginnis** [comment]
I'm going to assume this is working now. If not, please feel free to reopen the issue and give an update of what you see. Thanks!
