### ISSUE TITLE
tanzu-framework should produce signed binaries in each release and push those to target bucket

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/tanzu-framework#614]
**Describe the feature request**

Eventually, Tanzu Community Edition and other editions will re-use tanzu-framework produced binaries. Especially once we figure out:

* https://github.com/vmware-tanzu/tanzu-framework/issues/569

To achieve this, the binaries should be signed so that they can be re-packaged by different edition.

**Describe alternatives you've considered**

None

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

**Comment by navidshaikh** [comment]
Per release, signed tanzu CLI and plugins are uploaded to [tanzu-cli-framework](https://console.cloud.google.com/storage/browser/tanzu-cli-framework) bucket as well as release page.
