### ISSUE TITLE
Add unit tests for Pinniped addon post deploy job

### ISSUE THREAD

**Issue by iancoffey** [vmware-tanzu/tanzu-framework#62]
**Describe the feature request**
When Pinniped post deploy job was added, the unit tests were missing. Adding a comprehensive unit tests could help catch bugs and prevent regression.

**Describe alternatives you've considered**
NA

**Affected product area (please put an X in all that apply)**

[ ] APIs
[x] Addons
[ ] CLI
[ ] Docs
[ ] Installation
[ ] Plugin
[ ] Security
[ ] Test and Release
[ ] User Experience

**Additional context**

**Comment by ankeesler** [comment]
the post-deploy job unit tests have been improved. see `git log --oneline -- addons/pinniped/post-deploy/**_test.go`
