### ISSUE TITLE
package plugin update command should be smarter

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/tanzu-framework#640]
**Bug description**
`tanzu package installed update  ...` requires to provide the version of an installed package even if one is only updating the configuration.

```
tanzu package installed update educates -f ~/eduk8s-config.yaml
Error: required flag(s) "version" not set
Usage:
  tanzu package installed update INSTALLED_PACKAGE_NAME --version VERSION [flags]

Examples:

    # Update installed package with name 'mypkg' with some version to version '3.0.0-rc.1' in specified namespace
    tanzu package installed update mypkg --version 3.0.0-rc.1 --namespace test-ns
```

**Affected product area (please put an X in all that apply)**

- [ ] CLI
- [ ] Docs
- [ ] Plugin
- [ ] User Experience

**Expected behavior**
It should not require --version as you want to update an existing packageinstall's configuration only, and this should be possible in an easy way, as defined in https://github.com/vmware-tanzu/tanzu-framework/issues/417

**Steps to reproduce the bug**
Try to update an installed package without providing a version.

**Version** (include the SHA if the version is not obvious)
tanzu package info
{"name":"package","description":"Tanzu package management","version":"v1.4.0","buildSHA":"c9929b8f","group":"Run","docURL":"","completionType":0}

**Comment by maralavi** [comment]
This issue has been fixed in https://github.com/vmware-tanzu/tanzu-framework/pull/462
