### ISSUE TITLE
Addons controller support for cluster api v1beta1

### ISSUE THREAD

**Issue by shyaamsn** [vmware-tanzu/tanzu-framework#654]
(This is used to request new product features)

**Describe the feature request**
Addons controller support for cluster api v1beta1. Cluster api v1beta1 support k8s1.22. In order to support k8s1.22 addons controller has to support cluster api v1beta1

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [ ] CLI
- [ ] Docs
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

**Comment by danniel1205** [comment]
changes are merged as part of https://github.com/vmware-tanzu/tanzu-framework/pull/927
