### ISSUE TITLE
Manage Packaging Tooling

### ISSUE THREAD

**Issue by iancoffey** [vmware-tanzu/tanzu-framework#69]
**Describe the feature request**
We want to make it easy for controller developers to package their controllers using carvel tooling, to do that we would need a CLI plugin that has some commands to generate package contents, push them to the registry, add them to the package repository, etc.,

These commands would be used in the make targets in the Makefile that will be generated with the new controller scaffolding framework that we are working on.

**Affected product area (please put an X in all that apply)**

[x] APIs
[ ] Addons
[x] CLI
[ ] Docs
[ ] Installation
[ ] Plugin
[ ] Security
[ ] Test and Release
[x] User Experience

**Additional context**

### Collated Context

Context from 2021-06-21 18:38:22
User: iancoffey
Acceptance:
- separate package builder CLI plugin
- docs and best practices

**Comment by yharish991** [comment]
resolved this with PR https://github.com/vmware-tanzu/tanzu-framework/pull/975
