### ISSUE TITLE
test: Integration tests CAPD failing; timed out waiting for cluster creation to complete

### ISSUE THREAD

**Issue by navidshaikh** [vmware-tanzu/tanzu-framework#714]
**Bug description**

Test failing for CAPD integration tests:
Excerpts from logs:
```
469: timed out waiting for cluster creation to complete: cluster control plane is still being initialized: ScalingUp
```
ref: [logs](https://github.com/vmware-tanzu/tanzu-framework/runs/3746953464?check_suite_focus=true)

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [ ] CLI
- [ ] Docs
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [x] Test and Release
- [ ] User Experience

**Expected behavior**
Tests do not flake.

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)
6d094c8

**Environment where the bug was observed (cloud, OS, etc)**
CI

**Relevant Debug Output (Logs, manifests, etc)**
See: https://github.com/vmware-tanzu/tanzu-framework/actions/workflows/tkg_integration_tests.yaml?query=is%3Afailure

**Comment by yzaccc** [comment]
Solved by upgrade to use kind from 0.8 to 0.11 in CAPD/CAPI, and kind itself in tkg-bom.

**Comment by yzaccc** [comment]
@vuil can I get permission to close the issues in this repo?

**Comment by navidshaikh** [comment]
thanks @yzaccc !

ping @vuil for the above request for Zac!
