### ISSUE TITLE
Update tanzu imagepullsecret command to tanzu secret registry

### ISSUE THREAD

**Issue by shyaamsn** [vmware-tanzu/tanzu-framework#723]
Update tanzu imagepullsecret command to tanzu secret registry create/delete/update/get/list

**Comment by maralavi** [comment]
PR sent 
https://github.com/vmware-tanzu/tanzu-framework/pull/810

@cppforlife As changes are already made under for the registry root command (secret of type registry), I didn't clarify the warning message further.
