### ISSUE TITLE
check-license.sh should ignore external repos

### ISSUE THREAD

**Issue by vijaykatam** [vmware-tanzu/tanzu-framework#740]
**Bug description**
pinniped git repo is cloned when building CLI locally, when running `make lint` it results in the following 

```
# Check licenses in shell scripts and Makefile
hack/check-license.sh
Checking License in shell scripts and Makefiles ...
No required license header found in:
   ./pinniped/hack/check-copyright-year.sh
   ./pinniped/hack/get-ldflags.sh
   ./pinniped/hack/kind-down.sh
   ./pinniped/hack/kind-up.sh
   ./pinniped/hack/lib/update-codegen.sh
   ./pinniped/hack/lib/verify-codegen.sh
   ./pinniped/hack/lib/version.sh
   ./pinniped/hack/module.sh
   ./pinniped/hack/prepare-for-integration-tests.sh
   ./pinniped/hack/tilt-down.sh
   ./pinniped/hack/tilt-up.sh
   ./pinniped/hack/update.sh
   ./pinniped/hack/verify.sh
License check failed!
Please add the license in each listed file and verify using './hack/check-license.sh'
make: *** [lint] Error 1
```

Related PR https://github.com/vmware-tanzu/tanzu-framework/pull/716

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
Ignore external git repos such as pinniped

**Steps to reproduce the bug** 
`make lint`

**Comment by danniel1205** [comment]
I think the linter wants to ignore vendor dir as well.

The following are the output when running `make lint` from my local

```
vendor/sigs.k8s.io/yaml/README.md:116:1 MD010/no-hard-tabs Hard tabs [Column: 1]
vendor/sigs.k8s.io/yaml/README.md:117:1 MD010/no-hard-tabs Hard tabs [Column: 1]
vendor/sigs.k8s.io/yaml/README.md:118:1 MD010/no-hard-tabs Hard tabs [Column: 1]
vendor/sigs.k8s.io/yaml/README.md:119:1 MD010/no-hard-tabs Hard tabs [Column: 1]
vendor/sigs.k8s.io/yaml/README.md:120:1 MD010/no-hard-tabs Hard tabs [Column: 1]
vendor/sigs.k8s.io/yaml/README.md:121:1 MD010/no-hard-tabs Hard tabs [Column: 1]
```

**Comment by stmcginnis** [comment]
> I think the linter wants to ignore vendor dir as well.

This errors are actually from the markdownlint checks, so that might be better filed as a separate issue.

But I don't see a vendor dir in use. Is that a leftover of an old version or something? We can add it to the list of dirs that are skipped by mdlint, but I'd like to understand why I'm not seeing that (nor are the check jobs).

**Comment by vuil** [comment]
@navidshaikh please take a look
