### ISSUE TITLE
Make number of machines customizable for management clusters

### ISSUE THREAD

**Issue by saji-pivotal** [vmware-tanzu/tanzu-framework#746]
(This is used to request new product features)

**Describe the feature request**
Currently there are only 2 configurations that can be used while creating a management cluster
1. The Dev plan which creates a management cluster with 1 control-plane node, and 1 worker node
2. The Prod plan which creates a management cluster with 1 control-plane node and 3 worker nodes

The plans are very limiting. There are a couple asks as part of this feature
1. Increase the default number of control plane machines to 3 for prod management clusters
2. Allow users to customize the number of control-plane machines they want as part of the management cluster

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [X] CLI
- [ ] Docs
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [X] User Experience

**Additional context**

**Comment by danniel1205** [comment]
>This feature has been implemented in #645

@saji-pivotal , could you help close this issue if it has been implemented and no longer valid ? thanks
