### ISSUE TITLE
Installer UI not showing logs or other information

### ISSUE THREAD

**Issue by djschny** [vmware-tanzu/tanzu-framework#786]
## Bug Report

After pressing the `DEPLOY MANAGEMENT CLUSTER` button in the UI, it advances to a screen that looks like it should be showing logs and has a `Deploy on` text but nothing ever shows up. If you go back to the terminal where the UI was launched from you can see logs being outputted there.

## Expected Behavior

The UI screen to provide feedback and logs.

## Steps to Reproduce the Bug

Create a Docker management cluster using the default settings and press the `DEPLOY MANAGEMENT CLUSTER` button.

## Screenshots or additional information and context

<img width="1572" alt="Screen Shot 2021-10-06 at 10 22 45 AM" src="https://user-images.githubusercontent.com/129643/136225595-6a3fd2b6-9018-42bb-bb09-1ebd64d74b50.png">

Log output from the terminal:
```
tanzu management-cluster create --ui --bind 0.0.0.0:8888 --browser none

Validating the pre-requisites...
Serving kickstart UI at http://[::]:8888
Identity Provider not configured. Some authentication features won't work.
Validating configuration...
Using infrastructure provider docker:v0.3.23
Generating cluster configuration...
Setting up bootstrapper...
Bootstrapper created. Kubeconfig: /home/ubuntu/.kube-tkg/tmp/config_PvnMXTfc
Installing providers on bootstrapper...
Fetching providers
Installing cert-manager Version="v1.1.0"
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v0.3.23" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v0.3.23" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v0.3.23" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-docker" Version="v0.3.23" TargetNamespace="capd-system"
Start creating management cluster...
Saving management cluster kubeconfig into /home/ubuntu/.kube/config
```

## Environment Details

* Build version (`tanzu version`): `v0.9.1`
* Deployment (Managed/Standalone cluster): `Managed`
* Infrastructure Provider (Docker/AWS/Azure/vSphere): `Docker`
* Operating System (client): `Ubuntu`

**Comment by vmw-larry-yu** [comment]
Hi @djschny,

Given your situation, can you try a few other things:
1) Don't use any proxy in between (your laptop and AWS).
2) Note down the HOSTNAME/IP you used to access the Tanzu UI.
2) Instead of --bind 0.0.0.0:8888, try the IP or the HOSTNAME in lieu of 0.0.0.0.
