### ISSUE TITLE
Tanzu Plugin list is too wide

### ISSUE THREAD

**Issue by shyaamsn** [vmware-tanzu/tanzu-framework#822]
**Bug description**
tanzu plugin list is too wide because of imagepullsecret plugin desription. plugin list should probably truncate description to something resonable, and imagepullsecret plugin should have shorter description.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [x] CLI
- [ ] Docs
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by stmcginnis** [comment]
I wonder if we should consider an `-o wide` option that we could use to keep the default output more concise.

**Comment by shivaani0505** [comment]
Since we have now fixed the issue for renaming imagepullsecret plugin to `tanzu secret registry`, descriptions are now short.
Refer to [PR](https://github.com/vmware-tanzu/tanzu-framework/pull/810)

**Comment by nfisher-tkg** [comment]
Thank you @shivaani0505 , sorry I didn't see this until now and I was out yesterday.
