### ISSUE TITLE
Bump Pinniped to more recent (non-0.4.x) release

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/tanzu-framework#835]
This request originated in the community-edition repository.

## Feature Request
Update the Pinniped Version in TCE to use one of the newer releases of Pinniped. this would allow getting rid of Dex as there is now direct LDAP and even specific AD support which would allow for CLI base login which is great.
Also this would give a much better experience when running from a jump box without a browser as you dont need an additional terminal to paste the URL returned and its also exposed in a cleaner more understandable way.
this would also allow for OIDC providers that support the password grant auth flow (AzureAD for example) to support a CLI based login and not require a UI interaction.

## Describe alternatives you've considered
I currently deploy pinniped manually on my clusters as i need a good experience for jump boxes which currently problematic.
I use a custom api group similar to the way TMC does in order to not interfere with the pinniped deployed by TCE and the one deployed via TMC.
needing to have 3 pinnipeds seems like overkill and really not the best UX.
 

## Additional context
Getting rid of Dex would be great as its simply one less component to need to debug.
and if anyone needs Dex, they can configure Dex as the OIDC provider for identity management so no functionality is lost.

**Comment by saji-pivotal** [comment]
@joshrosso @andreasf Can you please close this issue out if all associated PRs have been merged?

**Comment by ankeesler** [comment]
fwiw, the new version of the pinniped package has not been integrated into the BOM that TCE uses yet. once that happens, the new version of the pinniped package should show up in TCE.

**Comment by andreasf** [comment]
> @joshrosso @andreasf Can you please close this issue out if all associated PRs have been merged?

Hi @saji-pivotal, I assume you meant @ankeesler instead of me?

**Comment by ankeesler** [comment]
oh hey! we did this! `tanzu` should have support for pinniped 0.12.0 as of  `v0.11.1`. note, though, that this feature depends on the BOM used with `tanzu`.
