### ISSUE TITLE
Bump go version to 1.17

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/tanzu-framework#857]
**Describe the feature request**

Go 1.17 has been out for awhile now, and upstream k8s and others have already transitioned to using it. It would be good for us to come up with an official policy describing how we want to handle go updates. In the meantime, filing this so we can track some of the steps that we need to perform when we do decide to update.

- [ ] Update all `go.mod` files to include `go 1.17.x`
- [ ] Run `go mod tidy -go=1.17` to update our go.mod files to pick up [module graph](https://golang.org/doc/go1.17#tools) changes
- [x] Update our version of golangci-lint to address a [panic in one of the linters](https://github.com/golangci/golangci-lint/issues/2222)

Will add others if they come up.

**Describe alternatives you've considered**

We can stay on 1.16, but there are improvements in newer version that we would miss out on.

**Comment by benjaminapetersen** [comment]
Nice, meanwhile it may be valuable to point out a recommended go version (1.16) in a `Development Setup` heading in the main README or CONTRIBUTING doc.
