### ISSUE TITLE
Kickstart UI should "recommend" some AWS instance types or be more selective in what it presents our users

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/tanzu-framework#861]
[This issue originated in community-edition. It's largely feedback that the instance size list is very overwhelming.](https://github.com/vmware-tanzu/community-edition/issues/2134)

## Details

We should provide a selective list or file some way to have a better UX for choosing an instance size.

**Comment by vrabbi** [comment]
Showimg thr name of thr tshirt size alomg with the resources that size contains would be a huge improvement. Also not showing unsupported types such as ARM ones, ones with not enough resources to meet the bare minimal reqs of tanzu makes sense i think and would give a better experience

**Comment by stmcginnis** [comment]
Reinforcing something vrabbi said earlier:

> Also not showing unsupported types such as ARM ones

We had feedback from the community today that this was a point of confusion for them. From Slack:

it will be great if ARM instance types are removed from the list to avoid `error The architecture 'arm64' of the specified instance type does not match the architecture 'x86_64' of the specified AMI`

**Comment by miclettej** [comment]
Sounds good, we'll start with filtering out these instance types.

**Comment by miclettej** [comment]
TODO: consider using config value for enable/disable filtering with regex as config value

**Comment by miclettej** [comment]
@stmcginnis the list of ARM-based instance families that I have to filter out are as follows:
M6g
T4g
A1

C7g
C6g
C6gn

R6g
X2gd

G5g

Im4gn
Is4gen

Will go ahead with this unless you have any objection
