### ISSUE TITLE
Bump kapp-controller to 0.27

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/tanzu-framework#872]
**Describe the feature request**
Bump kapp-controller to 0.27 to benefit from the speed improvements in reconciliation introduced in this version.
Keep in mind that 0.26 changed default syncPeriods of both PackageRepositories and PackageInstalls, so evaluate what the most appropriate value for TCE/TKG is (or make it configurable).

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [*] Addons
- [ ] CLI
- [ ] Docs
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

**Comment by shivaani0505** [comment]
Closing this issue as it is now obsolete ,  kapp controller is now upgraded to version 0.28.0 with #961
