### ISSUE TITLE
How to build a single built-in plugin for local iteration?

### ISSUE THREAD

**Issue by mamachanko** [vmware-tanzu/tanzu-framework#899]
Hi, I am trying to get myself set up for contributing. However, I struggle with building the one plugin that I am making changes to, installing it and testing my changes.

I understand that there're a couple of make targets that should help with this and there's `tanzu builder`, but I fail to set up a workflow.

Let's say I want to work on the `package` plugin:
1. As documented, on a clean checkout I do `make build-install-cli-local` which builds and installs all plugins for my local architecture.
1. Then I am making changes to e.g. `cmd/cli/plugin/package/package_install.go`
1. Then I am trying to rebuild the `package` plugin again without having to wait for all of `make build-install-cli-local`, but that fails:

```shell
$ tanzu builder cli compile --match package --version $(make version)
ℹ  building local repository at ./artifacts
ℹ  🐷 - building plugin at path "cmd/cli/plugin/package"
✖  🐷 - error: exit status 1
✖  🐷 - output: ✖  plugin "package" version cannot be empty; version "package" "" is not a valid semantic version
exit status 1

========
✖  🐷 - building plugin "cmd/cli/plugin/package" failed - exit status 1
Error: exit status 1

✖  exit status 1
```

`$(make version)` was my best guess for the `--version` parameter because it asks for the version of the root.

I am aware that tests and documentation are part of the process, but I would like to discover and get a feel for all the machinery before.

**Comment by saji-pivotal** [comment]
@mamachanko For now, can you try running `make build-cli-local` and see if the plugin you want is installed under `./artifacts/darwin/amd64/cli` ? You can then use `./artifacts/darwin/amd64/cli/<plugin_name>/<version>/tanzu-<plugin>-<arch>` to use the plugin. Please let me know if you test out the workaround I suggested.

**Comment by mamachanko** [comment]
> ./artifacts/darwin/amd64/cli/<plugin_name>/<version>/tanzu-<plugin>-<arch>

Thanks @saji-pivotal for the workaround. It does work!

However, `make build-cli-local` takes ~3mins on my machine. It builds all the plugins. Is that the recommended way of iterating on a built-in plugin? Is there a way to only built, say the `package` plugin without hand-crafting a `go build ...` command?

**Comment by chandrareddyp** [comment]
- This is not a bug, we need to pass the Version info as input value to `--ldflags` flag, here is eg:
- `tanzu builder cli compile --match package --ldflags "-X 'github.com/vmware-tanzu/tanzu-framework/pkg/v1/buildinfo.Version=v0.27.0-dev'"`
- As part of the fix https://github.com/vmware-tanzu/tanzu-framework/pull/3289:

- [ ] - The flag `--version` is updated as optional
- [ ] - New make target 'build-plugin-local' has been added to build local plugins.
