### ISSUE TITLE
FeatureGates integration with CLI 

### ISSUE THREAD

**Issue by iancoffey** [vmware-tanzu/tanzu-framework#91]
FeatureGates integration with CLI day 0 with cluster and managment cluster plugins

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

- [x] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**

**Comment by yharish991** [comment]
resolved this issue with PR https://github.com/vmware-tanzu/tanzu-framework/pull/1106
