### ISSUE TITLE
Tanzu plugin list should wrap description

### ISSUE THREAD

**Issue by danniel1205** [vmware-tanzu/tanzu-framework#921]
**Bug description**
Running `tanzu plugin list` will show a list of current available/installed plugins, however the long description causes a change line which messed up the output. Please see the following screenshot:

<img width="1666" alt="Screen Shot 2021-10-19 at 12 31 04 PM" src="https://user-images.githubusercontent.com/1971842/137978196-6b41d08d-47b3-46ff-ac03-5db77877fe31.png">

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] Installation
- [x] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

- All columns should support wrapping texts if they are too long.

**Steps to reproduce the bug**

- Run `tanzu plugin list`
- Without wide monitor (or resize your terminal window), you will see the output gets messed up.

**Version** (include the SHA if the version is not obvious)

- Latest tanzu framework build.

**Environment where the bug was observed (cloud, OS, etc)**

- Mac OS with iTerm2

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by shyaamsn** [comment]
The long description for imagepullsecret is not there now since it has been modified to a shorter one as part of changing imagepullsecret to secret. But however we can retain this for wrapping long descriptions.

**Comment by codegold79** [comment]
PR #1839 has been submitted with a fix.
